module

public import MovingSofa.Gerver.RomikCalc

/-!
# The reduced system for the parameters of Gerver's sofa

This file was generated by a Python script; every step is an explicit, checked inequality, so the
    file
is self-contained. It defines, as polynomials in the "atoms"
`φ, θ, c = cos φ, s = sin φ, C = cos θ, S = sin θ, p = π`:

* the reduced system `H = (rom_H1, rom_H2)` whose zeros in the box are the angles `(φ, θ)` of the
  solutions of Romik's system (see `MovingSofa.Gerver.Romik`), and its partial derivatives;
* the Newton-type map `G(z) = z - M H(z)` (`rom_G1`, `rom_G2`, with `M ≈ DH(z*)⁻¹`) and its partial
  derivatives;
* the linear parameters `a₁, b₁, b₂, c₁, κ_{j}` of a solution as functions of the atoms.

It proves the derivative formulas (`*_hasDerivAt_φ`, `*_hasDerivAt_θ`), and enclosures by interval
arithmetic (each step is checked by `norm_num`) in three regimes:

* `_box`: for `(φ, θ) ∈ [0.039, 0.04] × [0.68, 0.69]` (bounds on the derivatives of `G`, which make
  `G` a contraction there);
* `_z0`: at `(φ₀, θ₀) = (0.0391773648, 0.6813015094)` (the residual `M H(φ₀, θ₀)` is below
    `2·10⁻¹¹`);
* `_tiny`: for `|φ - φ₀|, |θ - θ₀| ≤ 10⁻¹⁰` (enclosures of the parameters of the solution).
-/

@[expose] public section

open Real Set

namespace MovingSofa

/-! ### Definitions -/

/-- The quantity `K = π/2 - 3/2 - θ + θ²/4`. -/
noncomputable def rom_K (θ p : ℝ) : ℝ :=
  ((((p / 2) - 3 / 2) - θ) + ((θ * θ) / 4))

/-- `∂K/∂θ`. -/
noncomputable def rom_Kθ (θ : ℝ) : ℝ :=
  ((θ / 2) - 1)

/-- The coefficient `D = 2 cos φ - (2 + θ - φ) sin φ` of `a₁`. -/
noncomputable def rom_D (φ θ c s : ℝ) : ℝ :=
  ((2 * c) - (((2 + θ) - φ) * s))

/-- The numerator `N_b` of `b₁ = N_b / D`. -/
noncomputable def rom_Nb (φ θ c s p : ℝ) : ℝ :=
  ((c * ((φ - 1 / 2) - (c / 2))) - (s * ((((s / 2) - ((φ * φ) / 4)) + (rom_K θ p)) + 3 / 2)))

/-- The first component of `U`. -/
noncomputable def rom_U1 (φ θ c s C S p : ℝ) : ℝ :=
  ((((-(c * ((rom_K θ p) - ((φ * φ) / 4)))) + (s * ((φ / 2) - 1))) + ((3 * C) / 2)) + (S * (((3 * θ)
      / 2) - 3)))

/-- The first component of `V`. -/
noncomputable def rom_V1 (φ θ c s S : ℝ) : ℝ :=
  (((c * ((2 + θ) - φ)) - s) - (3 * S))

/-- The second component of `U`. -/
noncomputable def rom_U2 (φ θ c s C S p : ℝ) : ℝ :=
  ((((-(s * ((rom_K θ p) - ((φ * φ) / 4)))) - (c * ((φ / 2) - 1))) - (S / 2)) + (C * ((θ / 2) - 1)))

/-- The second component of `V`. -/
noncomputable def rom_V2 (φ θ c s C : ℝ) : ℝ :=
  (((s * ((2 + θ) - φ)) + c) - C)

/-- The first component of `H = D U + N_b V`. -/
noncomputable def rom_H1 (φ θ c s C S p : ℝ) : ℝ :=
  (((rom_D φ θ c s) * (rom_U1 φ θ c s C S p)) + ((rom_Nb φ θ c s p) * (rom_V1 φ θ c s S)))

/-- The second component of `H = D U + N_b V`. -/
noncomputable def rom_H2 (φ θ c s C S p : ℝ) : ℝ :=
  (((rom_D φ θ c s) * (rom_U2 φ θ c s C S p)) + ((rom_Nb φ θ c s p) * (rom_V2 φ θ c s C)))

/-- `∂D/∂φ`. -/
noncomputable def rom_Dφ (φ θ c s : ℝ) : ℝ :=
  ((c * ((φ - θ) - 2)) - s)

/-- `∂D/∂θ`. -/
noncomputable def rom_Dθ (s : ℝ) : ℝ :=
  (-s)

/-- `∂N_b/∂φ`. -/
noncomputable def rom_Nbφ (φ θ c s p : ℝ) : ℝ :=
  ((c * ((((φ * φ) / 4) - (rom_K θ p)) - 1 / 2)) + ((s * (1 - φ)) / 2))

/-- `∂N_b/∂θ`. -/
noncomputable def rom_Nbθ (θ s : ℝ) : ℝ :=
  (s * (1 - (θ / 2)))

/-- `∂U₁/∂φ`. -/
noncomputable def rom_U1φ (φ θ c s p : ℝ) : ℝ :=
  ((s * (((rom_K θ p) - ((φ * φ) / 4)) + 1 / 2)) + (c * (φ - 1)))

/-- `∂U₁/∂θ`. -/
noncomputable def rom_U1θ (θ c C : ℝ) : ℝ :=
  ((-(c * ((θ / 2) - 1))) + (C * (((3 * θ) / 2) - 3)))

/-- `∂V₁/∂φ`. -/
noncomputable def rom_V1φ (φ θ c s : ℝ) : ℝ :=
  ((-(s * ((2 + θ) - φ))) - (2 * c))

/-- `∂V₁/∂θ`. -/
noncomputable def rom_V1θ (c C : ℝ) : ℝ :=
  (c - (3 * C))

/-- `∂U₂/∂φ`. -/
noncomputable def rom_U2φ (φ θ c s p : ℝ) : ℝ :=
  ((-(c * (((rom_K θ p) - ((φ * φ) / 4)) + 1 / 2))) + (s * (φ - 1)))

/-- `∂U₂/∂θ`. -/
noncomputable def rom_U2θ (θ s S : ℝ) : ℝ :=
  ((s + S) * (1 - (θ / 2)))

/-- `∂V₂/∂φ`. -/
noncomputable def rom_V2φ (φ θ c s : ℝ) : ℝ :=
  ((c * ((2 + θ) - φ)) - (2 * s))

/-- `∂V₂/∂θ`. -/
noncomputable def rom_V2θ (s S : ℝ) : ℝ :=
  (s + S)

/-- `∂H₁/∂φ`. -/
noncomputable def rom_H1φ (φ θ c s C S p : ℝ) : ℝ :=
  (((((rom_Dφ φ θ c s) * (rom_U1 φ θ c s C S p)) + ((rom_D φ θ c s) * (rom_U1φ φ θ c s p))) +
      ((rom_Nbφ φ θ c s p) * (rom_V1 φ θ c s S))) + ((rom_Nb φ θ c s p) * (rom_V1φ φ θ c s)))

/-- `∂H₁/∂θ`. -/
noncomputable def rom_H1θ (φ θ c s C S p : ℝ) : ℝ :=
  (((((rom_Dθ s) * (rom_U1 φ θ c s C S p)) + ((rom_D φ θ c s) * (rom_U1θ θ c C))) + ((rom_Nbθ θ s) *
      (rom_V1 φ θ c s S))) + ((rom_Nb φ θ c s p) * (rom_V1θ c C)))

/-- `∂H₂/∂φ`. -/
noncomputable def rom_H2φ (φ θ c s C S p : ℝ) : ℝ :=
  (((((rom_Dφ φ θ c s) * (rom_U2 φ θ c s C S p)) + ((rom_D φ θ c s) * (rom_U2φ φ θ c s p))) +
      ((rom_Nbφ φ θ c s p) * (rom_V2 φ θ c s C))) + ((rom_Nb φ θ c s p) * (rom_V2φ φ θ c s)))

/-- `∂H₂/∂θ`. -/
noncomputable def rom_H2θ (φ θ c s C S p : ℝ) : ℝ :=
  (((((rom_Dθ s) * (rom_U2 φ θ c s C S p)) + ((rom_D φ θ c s) * (rom_U2θ θ s S))) + ((rom_Nbθ θ s) *
      (rom_V2 φ θ c s C))) + ((rom_Nb φ θ c s p) * (rom_V2θ s S)))

/-- The first component of the Newton map. -/
noncomputable def rom_G1 (φ θ c s C S p : ℝ) : ℝ :=
  (φ + ((0.1481 * (rom_H1 φ θ c s C S p)) + (0.2886 * (rom_H2 φ θ c s C S p))))

/-- The second component of the Newton map. -/
noncomputable def rom_G2 (φ θ c s C S p : ℝ) : ℝ :=
  (θ + ((2.7218 * (rom_H1 φ θ c s C S p)) - (0.6267 * (rom_H2 φ θ c s C S p))))

/-- `∂G₁/∂φ`. -/
noncomputable def rom_G1φ (φ θ c s C S p : ℝ) : ℝ :=
  (1 + ((0.1481 * (rom_H1φ φ θ c s C S p)) + (0.2886 * (rom_H2φ φ θ c s C S p))))

/-- `∂G₁/∂θ`. -/
noncomputable def rom_G1θ (φ θ c s C S p : ℝ) : ℝ :=
  ((0.1481 * (rom_H1θ φ θ c s C S p)) + (0.2886 * (rom_H2θ φ θ c s C S p)))

/-- `∂G₂/∂φ`. -/
noncomputable def rom_G2φ (φ θ c s C S p : ℝ) : ℝ :=
  ((2.7218 * (rom_H1φ φ θ c s C S p)) - (0.6267 * (rom_H2φ φ θ c s C S p)))

/-- `∂G₂/∂θ`. -/
noncomputable def rom_G2θ (φ θ c s C S p : ℝ) : ℝ :=
  (1 + ((2.7218 * (rom_H1θ φ θ c s C S p)) - (0.6267 * (rom_H2θ φ θ c s C S p))))

/-- The first component of `M H`. -/
noncomputable def rom_MH1 (φ θ c s C S p : ℝ) : ℝ :=
  ((0.1481 * (rom_H1 φ θ c s C S p)) + (0.2886 * (rom_H2 φ θ c s C S p)))

/-- The second component of `M H`. -/
noncomputable def rom_MH2 (φ θ c s C S p : ℝ) : ℝ :=
  ((2.7218 * (rom_H1 φ θ c s C S p)) - (0.6267 * (rom_H2 φ θ c s C S p)))

/-- The constant term `β₀` of `b₁ = β₀ - a₁ sin φ`. -/
noncomputable def rom_β₀ (φ c : ℝ) : ℝ :=
  (((φ - 1 / 2) - (c / 2)) / 2)

/-- The numerator of `a₁ = N / D`. -/
noncomputable def rom_N (φ θ c s p : ℝ) : ℝ :=
  (((((s / 2) - ((φ * φ) / 4)) + (rom_K θ p)) + 3 / 2) - (((2 + θ) - φ) * (rom_β₀ φ c)))

/-- The parameter `a₁`. -/
noncomputable def rom_a₁ (φ θ c s p : ℝ) : ℝ :=
  ((rom_N φ θ c s p) / (rom_D φ θ c s))

/-- The parameter `b₁`. -/
noncomputable def rom_b₁ (φ θ c s p : ℝ) : ℝ :=
  ((rom_β₀ φ c) - (s * (rom_a₁ φ θ c s p)))

/-- The parameter `b₂`. -/
noncomputable def rom_b₂ (φ θ c s p : ℝ) : ℝ :=
  ((rom_K θ p) - ((2 + θ) * (rom_b₁ φ θ c s p)))

/-- The parameter `c₁`. -/
noncomputable def rom_c₁ (φ θ c s p : ℝ) : ℝ :=
  (((p / 2) - 2) - (2 * (rom_b₁ φ θ c s p)))

/-- First coordinate of `w₁(φ) - w₂(φ)`. -/
noncomputable def rom_Δ₁ (φ θ c s p : ℝ) : ℝ :=
  (((((rom_a₁ φ θ c s p) * c) - (s / 4)) - 1) - (((-((φ * φ) / 4)) + ((rom_b₁ φ θ c s p) * φ)) +
      (rom_b₂ φ θ c s p)))

/-- Second coordinate of `w₁(φ) - w₂(φ)`. -/
noncomputable def rom_Δ₂ (φ θ c s p : ℝ) : ℝ :=
  ((((c / 4) + ((rom_a₁ φ θ c s p) * s)) - 1 / 2) - (((φ / 2) - (rom_b₁ φ θ c s p)) - 1))

/-- The first coordinate of `κ₂`. -/
noncomputable def rom_κ₂₁ (φ θ c s p : ℝ) : ℝ :=
  (((c * (rom_Δ₁ φ θ c s p)) - (s * (rom_Δ₂ φ θ c s p))) + (1 - (rom_a₁ φ θ c s p)))

/-- The second coordinate of `κ₂`. -/
noncomputable def rom_κ₂₂ (φ θ c s p : ℝ) : ℝ :=
  (((s * (rom_Δ₁ φ θ c s p)) + (c * (rom_Δ₂ φ θ c s p))) + 1 / 4)

/-- The first coordinate of `κ₃`. -/
noncomputable def rom_κ₃₁ (φ θ c s C S p : ℝ) : ℝ :=
  (((C / 2) - (S * ((1 + (rom_b₁ φ θ c s p)) - (θ / 2)))) + (rom_κ₂₁ φ θ c s p))

/-- The second coordinate of `κ₃`. -/
noncomputable def rom_κ₃₂ (φ θ c s C S p : ℝ) : ℝ :=
  (((S / 2) + (C * ((1 + (rom_b₁ φ θ c s p)) - (θ / 2)))) + (rom_κ₂₂ φ θ c s p))

/-- The first coordinate of `κ₄`. -/
noncomputable def rom_κ₄₁ (φ θ c s C S p : ℝ) : ℝ :=
  ((2 * (rom_κ₃₁ φ θ c s C S p)) - (rom_κ₂₁ φ θ c s p))

/-- The first coordinate of `κ₅`. -/
noncomputable def rom_κ₅₁ (φ θ c s C S p : ℝ) : ℝ :=
  (((2 * (rom_κ₃₁ φ θ c s C S p)) - 1) + (rom_a₁ φ θ c s p))

/-! ### Derivatives -/

theorem rom_K_hasDerivAt_θ (_x y : ℝ) :
    HasDerivAt (fun t => rom_K t π) (rom_Kθ y) y := by
  refine HasDerivAt.congr_deriv (((((hasDerivAt_const y π).div_const (2 : ℝ)).fun_sub
      (hasDerivAt_const y (3 / 2 : ℝ))).fun_sub (hasDerivAt_id' y)).fun_add
      (((hasDerivAt_id' y).fun_mul (hasDerivAt_id' y)).div_const (4 : ℝ))) ?_
  simp only [rom_Kθ]
  ring

theorem rom_D_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_D t y (cos t) (sin t)) (rom_Dφ x y (cos x) (sin x)) x := by
  refine HasDerivAt.congr_deriv (((hasDerivAt_const x (2 : ℝ)).fun_mul
      (Real.hasDerivAt_cos x)).fun_sub ((((hasDerivAt_const x (2 : ℝ)).fun_add
      (hasDerivAt_const x y)).fun_sub (hasDerivAt_id' x)).fun_mul (Real.hasDerivAt_sin x))) ?_
  simp only [rom_Dφ]
  ring

theorem rom_D_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_D x t (cos x) (sin x)) (rom_Dθ (sin x)) y := by
  refine HasDerivAt.congr_deriv (((hasDerivAt_const y (2 : ℝ)).fun_mul (hasDerivAt_const y
      (cos x))).fun_sub ((((hasDerivAt_const y (2 : ℝ)).fun_add (hasDerivAt_id' y)).fun_sub
      (hasDerivAt_const y x)).fun_mul (hasDerivAt_const y (sin x)))) ?_
  simp only [rom_Dθ]
  ring

theorem rom_Nb_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_Nb t y (cos t) (sin t) π) (rom_Nbφ x y (cos x) (sin x) π) x := by
  refine HasDerivAt.congr_deriv (((Real.hasDerivAt_cos x).fun_mul (((hasDerivAt_id' x).fun_sub
      (hasDerivAt_const x (1 / 2 : ℝ))).fun_sub ((Real.hasDerivAt_cos x).div_const
      (2 : ℝ)))).fun_sub ((Real.hasDerivAt_sin x).fun_mul (((((Real.hasDerivAt_sin x).div_const
      (2 : ℝ)).fun_sub (((hasDerivAt_id' x).fun_mul (hasDerivAt_id' x)).div_const (4 : ℝ))).fun_add
      (hasDerivAt_const x (rom_K y π))).fun_add (hasDerivAt_const x (3 / 2 : ℝ))))) ?_
  simp only [rom_Nbφ]
  ring

theorem rom_Nb_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_Nb x t (cos x) (sin x) π) (rom_Nbθ y (sin x)) y := by
  refine HasDerivAt.congr_deriv (((hasDerivAt_const y (cos x)).fun_mul
      (((hasDerivAt_const y x).fun_sub (hasDerivAt_const y (1 / 2 : ℝ))).fun_sub ((hasDerivAt_const
      y (cos x)).div_const (2 : ℝ)))).fun_sub ((hasDerivAt_const y (sin x)).fun_mul
      (((((hasDerivAt_const y (sin x)).div_const (2 : ℝ)).fun_sub (((hasDerivAt_const y x).fun_mul
      (hasDerivAt_const y x)).div_const (4 : ℝ))).fun_add (rom_K_hasDerivAt_θ x y)).fun_add
      (hasDerivAt_const y (3 / 2 : ℝ))))) ?_
  simp only [rom_Nbθ, rom_Kθ]
  ring

theorem rom_U1_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_U1 t y (cos t) (sin t) (cos y) (sin y) π) (rom_U1φ x y (cos x) (sin x)
        π) x := by
  refine HasDerivAt.congr_deriv ((((((Real.hasDerivAt_cos x).fun_mul ((hasDerivAt_const x
      (rom_K y π)).fun_sub (((hasDerivAt_id' x).fun_mul (hasDerivAt_id' x)).div_const
      (4 : ℝ)))).fun_neg).fun_add ((Real.hasDerivAt_sin x).fun_mul (((hasDerivAt_id' x).div_const
      (2 : ℝ)).fun_sub (hasDerivAt_const x (1 : ℝ))))).fun_add (((hasDerivAt_const x
      (3 : ℝ)).fun_mul (hasDerivAt_const x (cos y))).div_const (2 : ℝ))).fun_add ((hasDerivAt_const
      x (sin y)).fun_mul ((((hasDerivAt_const x (3 : ℝ)).fun_mul (hasDerivAt_const x y)).div_const
      (2 : ℝ)).fun_sub (hasDerivAt_const x (3 : ℝ))))) ?_
  simp only [rom_U1φ]
  ring

theorem rom_U1_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_U1 x t (cos x) (sin x) (cos t) (sin t) π) (rom_U1θ y (cos x) (cos y))
        y := by
  refine HasDerivAt.congr_deriv ((((((hasDerivAt_const y (cos x)).fun_mul
      ((rom_K_hasDerivAt_θ x y).fun_sub (((hasDerivAt_const y x).fun_mul
      (hasDerivAt_const y x)).div_const (4 : ℝ)))).fun_neg).fun_add ((hasDerivAt_const y
      (sin x)).fun_mul (((hasDerivAt_const y x).div_const (2 : ℝ)).fun_sub (hasDerivAt_const y
      (1 : ℝ))))).fun_add (((hasDerivAt_const y (3 : ℝ)).fun_mul (Real.hasDerivAt_cos y)).div_const
      (2 : ℝ))).fun_add ((Real.hasDerivAt_sin y).fun_mul ((((hasDerivAt_const y (3 : ℝ)).fun_mul
      (hasDerivAt_id' y)).div_const (2 : ℝ)).fun_sub (hasDerivAt_const y (3 : ℝ))))) ?_
  simp only [rom_U1θ, rom_Kθ]
  ring

theorem rom_V1_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_V1 t y (cos t) (sin t) (sin y)) (rom_V1φ x y (cos x) (sin x)) x := by
  refine HasDerivAt.congr_deriv ((((Real.hasDerivAt_cos x).fun_mul (((hasDerivAt_const x
      (2 : ℝ)).fun_add (hasDerivAt_const x y)).fun_sub (hasDerivAt_id' x))).fun_sub
      (Real.hasDerivAt_sin x)).fun_sub ((hasDerivAt_const x (3 : ℝ)).fun_mul (hasDerivAt_const x
      (sin y)))) ?_
  simp only [rom_V1φ]
  ring

theorem rom_V1_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_V1 x t (cos x) (sin x) (sin t)) (rom_V1θ (cos x) (cos y)) y := by
  refine HasDerivAt.congr_deriv ((((hasDerivAt_const y (cos x)).fun_mul (((hasDerivAt_const y
      (2 : ℝ)).fun_add (hasDerivAt_id' y)).fun_sub (hasDerivAt_const y x))).fun_sub
      (hasDerivAt_const y (sin x))).fun_sub ((hasDerivAt_const y (3 : ℝ)).fun_mul
      (Real.hasDerivAt_sin y))) ?_
  simp only [rom_V1θ]
  ring

theorem rom_U2_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_U2 t y (cos t) (sin t) (cos y) (sin y) π) (rom_U2φ x y (cos x) (sin x)
        π) x := by
  refine HasDerivAt.congr_deriv ((((((Real.hasDerivAt_sin x).fun_mul ((hasDerivAt_const x
      (rom_K y π)).fun_sub (((hasDerivAt_id' x).fun_mul (hasDerivAt_id' x)).div_const
      (4 : ℝ)))).fun_neg).fun_sub ((Real.hasDerivAt_cos x).fun_mul (((hasDerivAt_id' x).div_const
      (2 : ℝ)).fun_sub (hasDerivAt_const x (1 : ℝ))))).fun_sub ((hasDerivAt_const x
      (sin y)).div_const (2 : ℝ))).fun_add ((hasDerivAt_const x (cos y)).fun_mul
      (((hasDerivAt_const x y).div_const (2 : ℝ)).fun_sub (hasDerivAt_const x (1 : ℝ))))) ?_
  simp only [rom_U2φ]
  ring

theorem rom_U2_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_U2 x t (cos x) (sin x) (cos t) (sin t) π) (rom_U2θ y (sin x) (sin y))
        y := by
  refine HasDerivAt.congr_deriv ((((((hasDerivAt_const y (sin x)).fun_mul
      ((rom_K_hasDerivAt_θ x y).fun_sub (((hasDerivAt_const y x).fun_mul
      (hasDerivAt_const y x)).div_const (4 : ℝ)))).fun_neg).fun_sub ((hasDerivAt_const y
      (cos x)).fun_mul (((hasDerivAt_const y x).div_const (2 : ℝ)).fun_sub (hasDerivAt_const y
      (1 : ℝ))))).fun_sub ((Real.hasDerivAt_sin y).div_const (2 : ℝ))).fun_add
      ((Real.hasDerivAt_cos y).fun_mul (((hasDerivAt_id' y).div_const (2 : ℝ)).fun_sub
      (hasDerivAt_const y (1 : ℝ))))) ?_
  simp only [rom_U2θ, rom_Kθ]
  ring

theorem rom_V2_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_V2 t y (cos t) (sin t) (cos y)) (rom_V2φ x y (cos x) (sin x)) x := by
  refine HasDerivAt.congr_deriv ((((Real.hasDerivAt_sin x).fun_mul (((hasDerivAt_const x
      (2 : ℝ)).fun_add (hasDerivAt_const x y)).fun_sub (hasDerivAt_id' x))).fun_add
      (Real.hasDerivAt_cos x)).fun_sub (hasDerivAt_const x (cos y))) ?_
  simp only [rom_V2φ]
  ring

theorem rom_V2_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_V2 x t (cos x) (sin x) (cos t)) (rom_V2θ (sin x) (sin y)) y := by
  refine HasDerivAt.congr_deriv ((((hasDerivAt_const y (sin x)).fun_mul (((hasDerivAt_const y
      (2 : ℝ)).fun_add (hasDerivAt_id' y)).fun_sub (hasDerivAt_const y x))).fun_add
      (hasDerivAt_const y (cos x))).fun_sub (Real.hasDerivAt_cos y)) ?_
  simp only [rom_V2θ]
  ring

theorem rom_H1_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_H1 t y (cos t) (sin t) (cos y) (sin y) π) (rom_H1φ x y (cos x) (sin x)
        (cos y) (sin y) π) x := by
  refine HasDerivAt.congr_deriv (((rom_D_hasDerivAt_φ x y).fun_mul
      (rom_U1_hasDerivAt_φ x y)).fun_add ((rom_Nb_hasDerivAt_φ x y).fun_mul
      (rom_V1_hasDerivAt_φ x y))) ?_
  simp only [rom_H1φ]
  ring

theorem rom_H1_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_H1 x t (cos x) (sin x) (cos t) (sin t) π) (rom_H1θ x y (cos x) (sin x)
        (cos y) (sin y) π) y := by
  refine HasDerivAt.congr_deriv (((rom_D_hasDerivAt_θ x y).fun_mul
      (rom_U1_hasDerivAt_θ x y)).fun_add ((rom_Nb_hasDerivAt_θ x y).fun_mul
      (rom_V1_hasDerivAt_θ x y))) ?_
  simp only [rom_H1θ]
  ring

theorem rom_H2_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_H2 t y (cos t) (sin t) (cos y) (sin y) π) (rom_H2φ x y (cos x) (sin x)
        (cos y) (sin y) π) x := by
  refine HasDerivAt.congr_deriv (((rom_D_hasDerivAt_φ x y).fun_mul
      (rom_U2_hasDerivAt_φ x y)).fun_add ((rom_Nb_hasDerivAt_φ x y).fun_mul
      (rom_V2_hasDerivAt_φ x y))) ?_
  simp only [rom_H2φ]
  ring

theorem rom_H2_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_H2 x t (cos x) (sin x) (cos t) (sin t) π) (rom_H2θ x y (cos x) (sin x)
        (cos y) (sin y) π) y := by
  refine HasDerivAt.congr_deriv (((rom_D_hasDerivAt_θ x y).fun_mul
      (rom_U2_hasDerivAt_θ x y)).fun_add ((rom_Nb_hasDerivAt_θ x y).fun_mul
      (rom_V2_hasDerivAt_θ x y))) ?_
  simp only [rom_H2θ]
  ring

theorem rom_G1_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_G1 t y (cos t) (sin t) (cos y) (sin y) π) (rom_G1φ x y (cos x) (sin x)
        (cos y) (sin y) π) x := by
  refine HasDerivAt.congr_deriv ((hasDerivAt_id' x).fun_add (((hasDerivAt_const x
      (0.1481 : ℝ)).fun_mul (rom_H1_hasDerivAt_φ x y)).fun_add ((hasDerivAt_const x
      (0.2886 : ℝ)).fun_mul (rom_H2_hasDerivAt_φ x y)))) ?_
  simp only [rom_G1φ]
  ring

theorem rom_G1_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_G1 x t (cos x) (sin x) (cos t) (sin t) π) (rom_G1θ x y (cos x) (sin x)
        (cos y) (sin y) π) y := by
  refine HasDerivAt.congr_deriv ((hasDerivAt_const y x).fun_add (((hasDerivAt_const y
      (0.1481 : ℝ)).fun_mul (rom_H1_hasDerivAt_θ x y)).fun_add ((hasDerivAt_const y
      (0.2886 : ℝ)).fun_mul (rom_H2_hasDerivAt_θ x y)))) ?_
  simp only [rom_G1θ]
  ring

theorem rom_G2_hasDerivAt_φ (x y : ℝ) :
    HasDerivAt (fun t => rom_G2 t y (cos t) (sin t) (cos y) (sin y) π) (rom_G2φ x y (cos x) (sin x)
        (cos y) (sin y) π) x := by
  refine HasDerivAt.congr_deriv ((hasDerivAt_const x y).fun_add (((hasDerivAt_const x
      (2.7218 : ℝ)).fun_mul (rom_H1_hasDerivAt_φ x y)).fun_sub ((hasDerivAt_const x
      (0.6267 : ℝ)).fun_mul (rom_H2_hasDerivAt_φ x y)))) ?_
  simp only [rom_G2φ]
  ring

theorem rom_G2_hasDerivAt_θ (x y : ℝ) :
    HasDerivAt (fun t => rom_G2 x t (cos x) (sin x) (cos t) (sin t) π) (rom_G2θ x y (cos x) (sin x)
        (cos y) (sin y) π) y := by
  refine HasDerivAt.congr_deriv ((hasDerivAt_id' y).fun_add (((hasDerivAt_const y
      (2.7218 : ℝ)).fun_mul (rom_H1_hasDerivAt_θ x y)).fun_sub ((hasDerivAt_const y
      (0.6267 : ℝ)).fun_mul (rom_H2_hasDerivAt_θ x y)))) ?_
  simp only [rom_G2θ]
  ring

/-! ### Enclosures on the box `[0.039, 0.04] × [0.68, 0.69]` -/

theorem rom_K_box {θ p : ℝ}
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_K θ p ∈ Icc (-0.503604 : ℝ) (-0.4901785 : ℝ) := by
  have h1 := rom_iv_div (L := (1.570796 : ℝ)) (U := (1.5707965 : ℝ)) hp (k := 2) (by norm_num)
  have h2 := rom_iv_sub (L := (0.070796 : ℝ)) (U := (0.0707965 : ℝ)) h1 (rom_iv_self (3 / 2 : ℝ))
      (by norm_num)
  have h3 := rom_iv_sub (L := (-0.619204 : ℝ)) (U := (-0.6092035 : ℝ)) h2 hθ (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.4624 : ℝ)) (U := (0.4761 : ℝ)) hθ hθ (by norm_num)
  have h5 := rom_iv_div (L := (0.1156 : ℝ)) (U := (0.119025 : ℝ)) h4 (k := 4) (by norm_num)
  have h6 := rom_iv_add (L := (-0.503604 : ℝ)) (U := (-0.4901785 : ℝ)) h3 h5 (by norm_num)
  exact h6

theorem rom_D_box {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_D φ θ c s ∈ Icc (1.8923884882 : ℝ) (1.8970660986 : ℝ) := by
  have h1 := rom_iv_mul_nn (L := (1.9984002132 : ℝ)) (U := (2 : ℝ)) (rom_iv_self (2 : ℝ)) hc
      (by norm_num)
  have h2 := rom_iv_add (L := (2.68 : ℝ)) (U := (2.69 : ℝ)) (rom_iv_self (2 : ℝ)) hθ (by norm_num)
  have h3 := rom_iv_sub (L := (2.64 : ℝ)) (U := (2.651 : ℝ)) h2 hφ (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.1029339014 : ℝ)) (U := (0.106011725 : ℝ)) h3 hs (by norm_num)
  have h5 := rom_iv_sub (L := (1.8923884882 : ℝ)) (U := (1.8970660986 : ℝ)) h1 h4 (by norm_num)
  exact h5

theorem rom_Nb_box {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_Nb φ θ c s p ∈ Icc (-1.002166457 : ℝ) (-0.9984265877 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_sub (L := (-0.461 : ℝ)) (U := (-0.46 : ℝ)) hφ (rom_iv_self (1 / 2 : ℝ))
      (by norm_num)
  have h3 := rom_iv_div (L := (0.4996000533 : ℝ)) (U := (0.5 : ℝ)) hc (k := 2) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.961 : ℝ)) (U := (-0.9596000533 : ℝ)) h2 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.961 : ℝ)) (U := (-0.9588324755 : ℝ)) hc h4 (by norm_num)
  have h6 := rom_iv_div (L := (0.0194950571 : ℝ)) (U := (0.0199946671 : ℝ)) hs (k := 2)
      (by norm_num)
  have h7 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h8 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h7 (k := 4) (by norm_num)
  have h9 := rom_iv_sub (L := (0.0190950571 : ℝ)) (U := (0.0196144171 : ℝ)) h6 h8 (by norm_num)
  have h10 := rom_iv_add (L := (-0.4845089429 : ℝ)) (U := (-0.4705640829 : ℝ)) h9 h1 (by norm_num)
  have h11 := rom_iv_add (L := (1.0154910571 : ℝ)) (U := (1.0294359171 : ℝ)) h10 (rom_iv_self
      (3 / 2 : ℝ)) (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.0395941122 : ℝ)) (U := (0.041166457 : ℝ)) hs h11 (by norm_num)
  have h13 := rom_iv_sub (L := (-1.002166457 : ℝ)) (U := (-0.9984265877 : ℝ)) h5 h12 (by norm_num)
  exact h13

theorem rom_U1_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_U1 φ θ c s C S p ∈ Icc (0.3474822143 : ℝ) (0.3965744742 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h2 (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.504004 : ℝ)) (U := (-0.49055875 : ℝ)) h1 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.504004 : ℝ)) (U := (-0.4901663552 : ℝ)) hc h4 (by norm_num)
  have h6 := rom_iv_neg (L := (0.4901663552 : ℝ)) (U := (0.504004 : ℝ)) h5 (by norm_num)
  have h7 := rom_iv_div (L := (0.0195 : ℝ)) (U := (0.02 : ℝ)) hφ (k := 2) (by norm_num)
  have h8 := rom_iv_sub (L := (-0.9805 : ℝ)) (U := (-0.98 : ℝ)) h7 (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h9 := rom_iv_mul (L := (-0.0392095422 : ℝ)) (U := (-0.0382103119 : ℝ)) hs h8 (by norm_num)
  have h10 := rom_iv_add (L := (0.450956813 : ℝ)) (U := (0.4657936881 : ℝ)) h6 h9 (by norm_num)
  have h11 := rom_iv_mul_nn (L := (2.3137380447 : ℝ)) (U := (2.3327181564 : ℝ)) (rom_iv_self
      (3 : ℝ)) hC (by norm_num)
  have h12 := rom_iv_div (L := (1.1568690223 : ℝ)) (U := (1.1663590782 : ℝ)) h11 (k := 2)
      (by norm_num)
  have h13 := rom_iv_add (L := (1.6078258353 : ℝ)) (U := (1.6321527663 : ℝ)) h10 h12 (by norm_num)
  have h14 := rom_iv_mul_nn (L := (2.04 : ℝ)) (U := (2.07 : ℝ)) (rom_iv_self (3 : ℝ)) hθ
      (by norm_num)
  have h15 := rom_iv_div (L := (1.02 : ℝ)) (U := (1.035 : ℝ)) h14 (k := 2) (by norm_num)
  have h16 := rom_iv_sub (L := (-1.98 : ℝ)) (U := (-1.965 : ℝ)) h15 (rom_iv_self (3 : ℝ))
      (by norm_num)
  have h17 := rom_iv_mul (L := (-1.260343621 : ℝ)) (U := (-1.2355782921 : ℝ)) hS h16 (by norm_num)
  have h18 := rom_iv_add (L := (0.3474822143 : ℝ)) (U := (0.3965744742 : ℝ)) h13 h17 (by norm_num)
  exact h18

theorem rom_V1_box {φ θ c s S : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ)) :
    rom_V1 φ θ c s S ∈ Icc (0.6882874003 : ℝ) (0.7256308138 : ℝ) := by
  have h1 := rom_iv_add (L := (2.68 : ℝ)) (U := (2.69 : ℝ)) (rom_iv_self (2 : ℝ)) hθ (by norm_num)
  have h2 := rom_iv_sub (L := (2.64 : ℝ)) (U := (2.651 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (2.6378882814 : ℝ)) (U := (2.651 : ℝ)) hc h2 (by norm_num)
  have h4 := rom_iv_sub (L := (2.5978989472 : ℝ)) (U := (2.6120098858 : ℝ)) h3 hs (by norm_num)
  have h5 := rom_iv_mul_nn (L := (1.886379072 : ℝ)) (U := (1.9096115469 : ℝ)) (rom_iv_self (3 : ℝ))
      hS (by norm_num)
  have h6 := rom_iv_sub (L := (0.6882874003 : ℝ)) (U := (0.7256308138 : ℝ)) h4 h5 (by norm_num)
  exact h6

theorem rom_U2_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_U2 φ θ c s C S p ∈ Icc (0.1668764603 : ℝ) (0.1810921327 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h2 (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.504004 : ℝ)) (U := (-0.49055875 : ℝ)) h1 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.0201547844 : ℝ)) (U := (-0.0191269416 : ℝ)) hs h4 (by norm_num)
  have h6 := rom_iv_neg (L := (0.0191269416 : ℝ)) (U := (0.0201547844 : ℝ)) h5 (by norm_num)
  have h7 := rom_iv_div (L := (0.0195 : ℝ)) (U := (0.02 : ℝ)) hφ (k := 2) (by norm_num)
  have h8 := rom_iv_sub (L := (-0.9805 : ℝ)) (U := (-0.98 : ℝ)) h7 (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h9 := rom_iv_mul (L := (-0.9805 : ℝ)) (U := (-0.9792161044 : ℝ)) hc h8 (by norm_num)
  have h10 := rom_iv_sub (L := (0.998343046 : ℝ)) (U := (1.0006547844 : ℝ)) h6 h9 (by norm_num)
  have h11 := rom_iv_div (L := (0.314396512 : ℝ)) (U := (0.3182685912 : ℝ)) hS (k := 2)
      (by norm_num)
  have h12 := rom_iv_sub (L := (0.6800744548 : ℝ)) (U := (0.6862582724 : ℝ)) h10 h11 (by norm_num)
  have h13 := rom_iv_div (L := (0.34 : ℝ)) (U := (0.345 : ℝ)) hθ (k := 2) (by norm_num)
  have h14 := rom_iv_sub (L := (-0.66 : ℝ)) (U := (-0.655 : ℝ)) h13 (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h15 := rom_iv_mul (L := (-0.5131979945 : ℝ)) (U := (-0.5051661397 : ℝ)) hC h14 (by norm_num)
  have h16 := rom_iv_add (L := (0.1668764603 : ℝ)) (U := (0.1810921327 : ℝ)) h12 h15 (by norm_num)
  exact h16

theorem rom_V2_box {φ θ c s C : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ)) :
    rom_V2 φ θ c s C ∈ Icc (0.3245612892 : ℝ) (0.3347657101 : ℝ) := by
  have h1 := rom_iv_add (L := (2.68 : ℝ)) (U := (2.69 : ℝ)) (rom_iv_self (2 : ℝ)) hθ (by norm_num)
  have h2 := rom_iv_sub (L := (2.64 : ℝ)) (U := (2.651 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (0.1029339014 : ℝ)) (U := (0.106011725 : ℝ)) hs h2 (by norm_num)
  have h4 := rom_iv_add (L := (1.102134008 : ℝ)) (U := (1.106011725 : ℝ)) h3 hc (by norm_num)
  have h5 := rom_iv_sub (L := (0.3245612892 : ℝ)) (U := (0.3347657101 : ℝ)) h4 hC (by norm_num)
  exact h5

theorem rom_Dφ_box {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_Dφ φ θ c s ∈ Icc (-2.6909893342 : ℝ) (-2.6768783956 : ℝ) := by
  have h1 := rom_iv_sub (L := (-0.651 : ℝ)) (U := (-0.64 : ℝ)) hφ hθ (by norm_num)
  have h2 := rom_iv_sub (L := (-2.651 : ℝ)) (U := (-2.64 : ℝ)) h1 (rom_iv_self (2 : ℝ))
      (by norm_num)
  have h3 := rom_iv_mul (L := (-2.651 : ℝ)) (U := (-2.6378882814 : ℝ)) hc h2 (by norm_num)
  have h4 := rom_iv_sub (L := (-2.6909893342 : ℝ)) (U := (-2.6768783956 : ℝ)) h3 hs (by norm_num)
  exact h4

theorem rom_Dθ_box {s : ℝ}
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_Dθ s ∈ Icc (-0.0399893342 : ℝ) (-0.0389901142 : ℝ) := by
  have h1 := rom_iv_neg (L := (-0.0399893342 : ℝ)) (U := (-0.0389901142 : ℝ)) hs (by norm_num)
  exact h1

theorem rom_Nbφ_box {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_Nbφ φ θ c s p ∈ Icc (0.0092740048 : ℝ) (0.0232188751 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h2 (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (0.49055875 : ℝ)) (U := (0.504004 : ℝ)) h3 h1 (by norm_num)
  have h5 := rom_iv_sub (L := (-0.00944125 : ℝ)) (U := (0.004004 : ℝ)) h4 (rom_iv_self (1 / 2 : ℝ))
      (by norm_num)
  have h6 := rom_iv_mul (L := (-0.00944125 : ℝ)) (U := (0.004004 : ℝ)) hc h5 (by norm_num)
  have h7 := rom_iv_sub (L := (0.96 : ℝ)) (U := (0.961 : ℝ)) (rom_iv_self (1 : ℝ)) hφ (by norm_num)
  have h8 := rom_iv_mul_nn (L := (0.0374305096 : ℝ)) (U := (0.0384297502 : ℝ)) hs h7 (by norm_num)
  have h9 := rom_iv_div (L := (0.0187152548 : ℝ)) (U := (0.0192148751 : ℝ)) h8 (k := 2)
      (by norm_num)
  have h10 := rom_iv_add (L := (0.0092740048 : ℝ)) (U := (0.0232188751 : ℝ)) h6 h9 (by norm_num)
  exact h10

theorem rom_Nbθ_box {θ s : ℝ}
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_Nbθ θ s ∈ Icc (0.0255385248 : ℝ) (0.0263929606 : ℝ) := by
  have h1 := rom_iv_div (L := (0.34 : ℝ)) (U := (0.345 : ℝ)) hθ (k := 2) (by norm_num)
  have h2 := rom_iv_sub (L := (0.655 : ℝ)) (U := (0.66 : ℝ)) (rom_iv_self (1 : ℝ)) h1 (by norm_num)
  have h3 := rom_iv_mul_nn (L := (0.0255385248 : ℝ)) (U := (0.0263929606 : ℝ)) hs h2 (by norm_num)
  exact h3

theorem rom_U1φ_box {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_U1φ φ θ c s p ∈ Icc (-0.9611601173 : ℝ) (-0.9588545529 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h2 (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.504004 : ℝ)) (U := (-0.49055875 : ℝ)) h1 h3 (by norm_num)
  have h5 := rom_iv_add (L := (-0.004004 : ℝ)) (U := (0.00944125 : ℝ)) h4 (rom_iv_self (1 / 2 : ℝ))
      (by norm_num)
  have h6 := rom_iv_mul (L := (-0.0001601173 : ℝ)) (U := (0.0003775494 : ℝ)) hs h5 (by norm_num)
  have h7 := rom_iv_sub (L := (-0.961 : ℝ)) (U := (-0.96 : ℝ)) hφ (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h8 := rom_iv_mul (L := (-0.961 : ℝ)) (U := (-0.9592321023 : ℝ)) hc h7 (by norm_num)
  have h9 := rom_iv_add (L := (-0.9611601173 : ℝ)) (U := (-0.9588545529 : ℝ)) h6 h8 (by norm_num)
  exact h9

theorem rom_U1θ_box {θ c C : ℝ}
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ)) :
    rom_U1θ θ c C ∈ Icc (-0.8851179135 : ℝ) (-0.8554984192 : ℝ) := by
  have h1 := rom_iv_div (L := (0.34 : ℝ)) (U := (0.345 : ℝ)) hθ (k := 2) (by norm_num)
  have h2 := rom_iv_sub (L := (-0.66 : ℝ)) (U := (-0.655 : ℝ)) h1 (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h3 := rom_iv_mul (L := (-0.66 : ℝ)) (U := (-0.6544760698 : ℝ)) hc h2 (by norm_num)
  have h4 := rom_iv_neg (L := (0.6544760698 : ℝ)) (U := (0.66 : ℝ)) h3 (by norm_num)
  have h5 := rom_iv_mul_nn (L := (2.04 : ℝ)) (U := (2.07 : ℝ)) (rom_iv_self (3 : ℝ)) hθ
      (by norm_num)
  have h6 := rom_iv_div (L := (1.02 : ℝ)) (U := (1.035 : ℝ)) h5 (k := 2) (by norm_num)
  have h7 := rom_iv_sub (L := (-1.98 : ℝ)) (U := (-1.965 : ℝ)) h6 (rom_iv_self (3 : ℝ))
      (by norm_num)
  have h8 := rom_iv_mul (L := (-1.5395939833 : ℝ)) (U := (-1.5154984192 : ℝ)) hC h7 (by norm_num)
  have h9 := rom_iv_add (L := (-0.8851179135 : ℝ)) (U := (-0.8554984192 : ℝ)) h4 h8 (by norm_num)
  exact h9

theorem rom_V1φ_box {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_V1φ φ θ c s ∈ Icc (-2.106011725 : ℝ) (-2.1013341146 : ℝ) := by
  have h1 := rom_iv_add (L := (2.68 : ℝ)) (U := (2.69 : ℝ)) (rom_iv_self (2 : ℝ)) hθ (by norm_num)
  have h2 := rom_iv_sub (L := (2.64 : ℝ)) (U := (2.651 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (0.1029339014 : ℝ)) (U := (0.106011725 : ℝ)) hs h2 (by norm_num)
  have h4 := rom_iv_neg (L := (-0.106011725 : ℝ)) (U := (-0.1029339014 : ℝ)) h3 (by norm_num)
  have h5 := rom_iv_mul_nn (L := (1.9984002132 : ℝ)) (U := (2 : ℝ)) (rom_iv_self (2 : ℝ)) hc
      (by norm_num)
  have h6 := rom_iv_sub (L := (-2.106011725 : ℝ)) (U := (-2.1013341146 : ℝ)) h4 h5 (by norm_num)
  exact h6

theorem rom_V1θ_box {c C : ℝ}
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ)) :
    rom_V1θ c C ∈ Icc (-1.3335180498 : ℝ) (-1.3137380447 : ℝ) := by
  have h1 := rom_iv_mul_nn (L := (2.3137380447 : ℝ)) (U := (2.3327181564 : ℝ)) (rom_iv_self (3 : ℝ))
      hC (by norm_num)
  have h2 := rom_iv_sub (L := (-1.3335180498 : ℝ)) (U := (-1.3137380447 : ℝ)) hc h1 (by norm_num)
  exact h2

theorem rom_U2φ_box {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_U2φ φ θ c s p ∈ Icc (-0.0478710002 : ℝ) (-0.0334265096 : ℝ) := by
  have h1 := rom_K_box hθ hp
  have h2 := rom_iv_mul_nn (L := (0.001521 : ℝ)) (U := (0.0016 : ℝ)) hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038025 : ℝ)) (U := (0.0004 : ℝ)) h2 (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.504004 : ℝ)) (U := (-0.49055875 : ℝ)) h1 h3 (by norm_num)
  have h5 := rom_iv_add (L := (-0.004004 : ℝ)) (U := (0.00944125 : ℝ)) h4 (rom_iv_self (1 / 2 : ℝ))
      (by norm_num)
  have h6 := rom_iv_mul (L := (-0.004004 : ℝ)) (U := (0.00944125 : ℝ)) hc h5 (by norm_num)
  have h7 := rom_iv_neg (L := (-0.00944125 : ℝ)) (U := (0.004004 : ℝ)) h6 (by norm_num)
  have h8 := rom_iv_sub (L := (-0.961 : ℝ)) (U := (-0.96 : ℝ)) hφ (rom_iv_self (1 : ℝ))
      (by norm_num)
  have h9 := rom_iv_mul (L := (-0.0384297502 : ℝ)) (U := (-0.0374305096 : ℝ)) hs h8 (by norm_num)
  have h10 := rom_iv_add (L := (-0.0478710002 : ℝ)) (U := (-0.0334265096 : ℝ)) h7 h9 (by norm_num)
  exact h10

theorem rom_U2θ_box {θ s S : ℝ}
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ)) :
    rom_U2θ θ s S ∈ Icc (0.4373979555 : ℝ) (0.4465075009 : ℝ) := by
  have h1 := rom_iv_add (L := (0.6677831382 : ℝ)) (U := (0.6765265165 : ℝ)) hs hS (by norm_num)
  have h2 := rom_iv_div (L := (0.34 : ℝ)) (U := (0.345 : ℝ)) hθ (k := 2) (by norm_num)
  have h3 := rom_iv_sub (L := (0.655 : ℝ)) (U := (0.66 : ℝ)) (rom_iv_self (1 : ℝ)) h2 (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.4373979555 : ℝ)) (U := (0.4465075009 : ℝ)) h1 h3 (by norm_num)
  exact h4

theorem rom_V2φ_box {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ)) :
    rom_V2φ φ θ c s ∈ Icc (2.557909613 : ℝ) (2.5730197716 : ℝ) := by
  have h1 := rom_iv_add (L := (2.68 : ℝ)) (U := (2.69 : ℝ)) (rom_iv_self (2 : ℝ)) hθ (by norm_num)
  have h2 := rom_iv_sub (L := (2.64 : ℝ)) (U := (2.651 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (2.6378882814 : ℝ)) (U := (2.651 : ℝ)) hc h2 (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.0779802284 : ℝ)) (U := (0.0799786684 : ℝ)) (rom_iv_self (2 : ℝ))
      hs (by norm_num)
  have h5 := rom_iv_sub (L := (2.557909613 : ℝ)) (U := (2.5730197716 : ℝ)) h3 h4 (by norm_num)
  exact h5

theorem rom_V2θ_box {s S : ℝ}
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ)) :
    rom_V2θ s S ∈ Icc (0.6677831382 : ℝ) (0.6765265165 : ℝ) := by
  have h1 := rom_iv_add (L := (0.6677831382 : ℝ)) (U := (0.6765265165 : ℝ)) hs hS (by norm_num)
  exact h1

theorem rom_H1φ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_H1φ φ θ c s C S p ∈ Icc (-0.786150924 : ℝ) (-0.6172703098 : ℝ) := by
  have h1 := rom_D_box hφ hθ hc hs
  have h2 := rom_Dφ_box hφ hθ hc hs
  have h3 := rom_Nb_box hφ hθ hc hs hp
  have h4 := rom_Nbφ_box hφ hθ hc hs hp
  have h5 := rom_U1_box hφ hθ hc hs hC hS hp
  have h6 := rom_U1φ_box hφ hθ hc hs hp
  have h7 := rom_V1_box hφ hθ hc hs hS
  have h8 := rom_V1φ_box hφ hθ hc hs
  have h9 := rom_iv_mul (L := (-1.0671776803 : ℝ)) (U := (-0.9301676323 : ℝ)) h2 h5 (by norm_num)
  have h10 := rom_iv_mul (L := (-1.8233842739 : ℝ)) (U := (-1.8145253177 : ℝ)) h1 h6 (by norm_num)
  have h11 := rom_iv_add (L := (-2.8905619542 : ℝ)) (U := (-2.74469295 : ℝ)) h9 h10 (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.0063831806 : ℝ)) (U := (0.0168483313 : ℝ)) h4 h7 (by norm_num)
  have h13 := rom_iv_add (L := (-2.8841787736 : ℝ)) (U := (-2.7278446187 : ℝ)) h11 h12 (by norm_num)
  have h14 := rom_iv_mul (L := (2.0980278496 : ℝ)) (U := (2.1105743089 : ℝ)) h3 h8 (by norm_num)
  have h15 := rom_iv_add (L := (-0.786150924 : ℝ)) (U := (-0.6172703098 : ℝ)) h13 h14 (by norm_num)
  exact h15

theorem rom_H1θ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_H1θ φ θ c s C S p ∈ Icc (-0.3657370983 : ℝ) (-0.2769251264 : ℝ) := by
  have h1 := rom_D_box hφ hθ hc hs
  have h2 := rom_Dθ_box hs
  have h3 := rom_Nb_box hφ hθ hc hs hp
  have h4 := rom_Nbθ_box hθ hs
  have h5 := rom_U1_box hφ hθ hc hs hC hS hp
  have h6 := rom_U1θ_box hθ hc hC
  have h7 := rom_V1_box hφ hθ hc hs hS
  have h8 := rom_V1θ_box hc hC
  have h9 := rom_iv_mul (L := (-0.0158587492 : ℝ)) (U := (-0.0135483712 : ℝ)) h2 h5 (by norm_num)
  have h10 := rom_iv_mul (L := (-1.679127187 : ℝ)) (U := (-1.6189353601 : ℝ)) h1 h6 (by norm_num)
  have h11 := rom_iv_add (L := (-1.6949859362 : ℝ)) (U := (-1.6324837313 : ℝ)) h9 h10 (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.0175778448 : ℝ)) (U := (0.0191515455 : ℝ)) h4 h7 (by norm_num)
  have h13 := rom_iv_add (L := (-1.6774080914 : ℝ)) (U := (-1.6133321858 : ℝ)) h11 h12 (by norm_num)
  have h14 := rom_iv_mul (L := (1.3116709931 : ℝ)) (U := (1.3364070594 : ℝ)) h3 h8 (by norm_num)
  have h15 := rom_iv_add (L := (-0.3657370983 : ℝ)) (U := (-0.2769251264 : ℝ)) h13 h14 (by norm_num)
  exact h15

theorem rom_H2φ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_H2φ φ θ c s C S p ∈ Icc (-3.1537155747 : ℝ) (-3.0560760164 : ℝ) := by
  have h1 := rom_D_box hφ hθ hc hs
  have h2 := rom_Dφ_box hφ hθ hc hs
  have h3 := rom_Nb_box hφ hθ hc hs hp
  have h4 := rom_Nbφ_box hφ hθ hc hs hp
  have h5 := rom_U2_box hφ hθ hc hs hC hS hp
  have h6 := rom_U2φ_box hφ hθ hc hs hp
  have h7 := rom_V2_box hφ hθ hc hs hC
  have h8 := rom_V2φ_box hφ hθ hc hs
  have h9 := rom_iv_mul (L := (-0.4873169977 : ℝ)) (U := (-0.4467079913 : ℝ)) h2 h5 (by norm_num)
  have h10 := rom_iv_mul (L := (-0.0908144516 : ℝ)) (U := (-0.0632559419 : ℝ)) h1 h6 (by norm_num)
  have h11 := rom_iv_add (L := (-0.5781314493 : ℝ)) (U := (-0.5099639332 : ℝ)) h9 h10 (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.0030099829 : ℝ)) (U := (0.0077728833 : ℝ)) h4 h7 (by norm_num)
  have h13 := rom_iv_add (L := (-0.5751214664 : ℝ)) (U := (-0.5021910499 : ℝ)) h11 h12 (by norm_num)
  have h14 := rom_iv_mul (L := (-2.5785941083 : ℝ)) (U := (-2.5538849665 : ℝ)) h3 h8 (by norm_num)
  have h15 := rom_iv_add (L := (-3.1537155747 : ℝ)) (U := (-3.0560760164 : ℝ)) h13 h14 (by norm_num)
  exact h15

theorem rom_H2θ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_H2θ φ θ c s C S p ∈ Icc (0.1507817361 : ℝ) (0.1826507289 : ℝ) := by
  have h1 := rom_D_box hφ hθ hc hs
  have h2 := rom_Dθ_box hs
  have h3 := rom_Nb_box hφ hθ hc hs hp
  have h4 := rom_Nbθ_box hθ hs
  have h5 := rom_U2_box hφ hθ hc hs hC hS hp
  have h6 := rom_U2θ_box hθ hs hS
  have h7 := rom_V2_box hφ hθ hc hs hC
  have h8 := rom_V2θ_box hs hS
  have h9 := rom_iv_mul (L := (-0.0072417539 : ℝ)) (U := (-0.0065065322 : ℝ)) h2 h5 (by norm_num)
  have h10 := rom_iv_mul_nn (L := (0.8277268557 : ℝ)) (U := (0.8470542428 : ℝ)) h1 h6 (by norm_num)
  have h11 := rom_iv_add (L := (0.8204851018 : ℝ)) (U := (0.8405477106 : ℝ)) h9 h10 (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.0082888165 : ℝ)) (U := (0.0088354582 : ℝ)) h4 h7 (by norm_num)
  have h13 := rom_iv_add (L := (0.8287739183 : ℝ)) (U := (0.8493831688 : ℝ)) h11 h12 (by norm_num)
  have h14 := rom_iv_mul (L := (-0.6779921822 : ℝ)) (U := (-0.6667324399 : ℝ)) h3 h8 (by norm_num)
  have h15 := rom_iv_add (L := (0.1507817361 : ℝ)) (U := (0.1826507289 : ℝ)) h13 h14 (by norm_num)
  exact h15

theorem rom_G1φ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_G1φ φ θ c s C S p ∈ Icc (-0.0265912668 : ℝ) (0.0265987289 : ℝ) := by
  have h1 := rom_H1φ_box hφ hθ hc hs hC hS hp
  have h2 := rom_H2φ_box hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-0.1164289519 : ℝ)) (U := (-0.0914177328 : ℝ)) (rom_iv_self
      (0.1481 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul (L := (-0.9101623149 : ℝ)) (U := (-0.8819835383 : ℝ)) (rom_iv_self
      (0.2886 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_add (L := (-1.0265912668 : ℝ)) (U := (-0.9734012711 : ℝ)) h3 h4 (by norm_num)
  have h6 := rom_iv_add (L := (-0.0265912668 : ℝ)) (U := (0.0265987289 : ℝ)) (rom_iv_self (1 : ℝ))
      h5 (by norm_num)
  exact h6

theorem rom_G1θ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_G1θ φ θ c s C S p ∈ Icc (-0.0106500553 : ℝ) (0.0117003892 : ℝ) := by
  have h1 := rom_H1θ_box hφ hθ hc hs hC hS hp
  have h2 := rom_H2θ_box hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-0.0541656643 : ℝ)) (U := (-0.0410126112 : ℝ)) (rom_iv_self
      (0.1481 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.043515609 : ℝ)) (U := (0.0527130004 : ℝ)) (rom_iv_self
      (0.2886 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_add (L := (-0.0106500553 : ℝ)) (U := (0.0117003892 : ℝ)) h3 h4 (by norm_num)
  exact h5

theorem rom_G2φ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_G2φ φ θ c s C S p ∈ Icc (-0.2245027456 : ℝ) (0.2963472215 : ℝ) := by
  have h1 := rom_H1φ_box hφ hθ hc hs hC hS hp
  have h2 := rom_H2φ_box hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-2.139745585 : ℝ)) (U := (-1.6800863292 : ℝ)) (rom_iv_self
      (2.7218 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul (L := (-1.9764335507 : ℝ)) (U := (-1.9152428394 : ℝ)) (rom_iv_self
      (0.6267 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_sub (L := (-0.2245027456 : ℝ)) (U := (0.2963472215 : ℝ)) h3 h4 (by norm_num)
  exact h5

theorem rom_G2θ_box {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.039 : ℝ) (0.04 : ℝ))
    (hθ : θ ∈ Icc (0.68 : ℝ) (0.69 : ℝ))
    (hc : c ∈ Icc (0.9992001066 : ℝ) (1 : ℝ))
    (hs : s ∈ Icc (0.0389901142 : ℝ) (0.0399893342 : ℝ))
    (hC : C ∈ Icc (0.7712460149 : ℝ) (0.7775727188 : ℝ))
    (hS : S ∈ Icc (0.628793024 : ℝ) (0.6365371823 : ℝ))
    (hp : p ∈ Icc (3.141592 : ℝ) (3.141593 : ℝ)) :
    rom_G2θ φ θ c s C S p ∈ Icc (-0.1099304461 : ℝ) (0.151770277 : ℝ) := by
  have h1 := rom_H1θ_box hφ hθ hc hs hC hS hp
  have h2 := rom_H2θ_box hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-0.9954632342 : ℝ)) (U := (-0.753734809 : ℝ)) (rom_iv_self
      (2.7218 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.094494914 : ℝ)) (U := (0.1144672119 : ℝ)) (rom_iv_self
      (0.6267 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_sub (L := (-1.1099304461 : ℝ)) (U := (-0.848229723 : ℝ)) h3 h4 (by norm_num)
  have h6 := rom_iv_add (L := (-0.1099304461 : ℝ)) (U := (0.151770277 : ℝ)) (rom_iv_self (1 : ℝ)) h5
      (by norm_num)
  exact h6

/-! ### Enclosures at `(φ₀, θ₀) = (0.0391773648, 0.6813015094)` -/

theorem rom_K_z0 {θ p : ℝ}
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_K θ p ∈ Icc (-0.49446224592742380868 : ℝ) (-0.494462245927423808675 : ℝ) := by
  have h1 := rom_iv_div (L := (1.57079632679489661923 : ℝ)) (U := (1.570796326794896619235 : ℝ)) hp
      (k := 2) (by norm_num)
  have h2 := rom_iv_sub (L := (0.07079632679489661923 : ℝ)) (U := (0.070796326794896619235 : ℝ)) h1
      (rom_iv_self (3 / 2 : ℝ)) (by norm_num)
  have h3 := rom_iv_sub (L := (-0.61050518260510338077 : ℝ)) (U := (-0.610505182605103380765 : ℝ))
      h2 hθ (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.46417174671071828836 : ℝ)) (U := (0.46417174671071828836 : ℝ))
      hθ hθ (by norm_num)
  have h5 := rom_iv_div (L := (0.11604293667767957209 : ℝ)) (U := (0.11604293667767957209 : ℝ)) h4
      (k := 4) (by norm_num)
  have h6 := rom_iv_add (L := (-0.49446224592742380868 : ℝ)) (U := (-0.494462245927423808675 : ℝ))
      h3 h5 (by norm_num)
  exact h6

theorem rom_D_z0 {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ)) :
    rom_D φ θ c s ∈ Icc (1.8949803462721035099009 : ℝ) (1.8949803462721037867751 : ℝ) := by
  have h1 := rom_iv_mul_nn (L := (1.9984653303950644955744 : ℝ)) (U := (1.998465330395064770865 :
      ℝ)) (rom_iv_self (2 : ℝ)) hc (by norm_num)
  have h2 := rom_iv_add (L := (2.6813015094 : ℝ)) (U := (2.6813015094 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h3 := rom_iv_sub (L := (2.6421241446 : ℝ)) (U := (2.6421241446 : ℝ)) h2 hφ (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.1034849841229609840899 : ℝ)) (U := (0.1034849841229609856735 :
      ℝ)) h3 hs (by norm_num)
  have h5 := rom_iv_sub (L := (1.8949803462721035099009 : ℝ)) (U := (1.8949803462721037867751 : ℝ))
      h1 h4 (by norm_num)
  exact h5

theorem rom_Nb_z0 {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_Nb φ θ c s p ∈ Icc (-0.9998382434842694631217 : ℝ) (-0.9998382434842692615256 : ℝ) := by
  have h1 := rom_K_z0 hθ hp
  have h2 := rom_iv_sub (L := (-0.4608226352 : ℝ)) (U := (-0.4608226352 : ℝ)) hφ (rom_iv_self
      (1 / 2 : ℝ)) (by norm_num)
  have h3 := rom_iv_div (L := (0.4996163325987661238936 : ℝ)) (U := (0.4996163325987661927163 : ℝ))
      hc (k := 2) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.9604389677987661927163 : ℝ)) (U := (-0.9604389677987661238936 :
      ℝ)) h2 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.9597019895531281268315 : ℝ)) (U := (-0.9597019895531279258616 :
      ℝ)) hc h4 (by norm_num)
  have h6 := rom_iv_div (L := (0.0195836717843982916854 : ℝ)) (U := (0.0195836717843982919851 : ℝ))
      hs (k := 2) (by norm_num)
  have h7 := rom_iv_mul_nn (L := (0.00153486591267227904 : ℝ)) (U := (0.00153486591267227904 : ℝ))
      hφ hφ (by norm_num)
  have h8 := rom_iv_div (L := (0.00038371647816806976 : ℝ)) (U := (0.00038371647816806976 : ℝ)) h7
      (k := 4) (by norm_num)
  have h9 := rom_iv_sub (L := (0.0191999553062302219254 : ℝ)) (U := (0.0191999553062302222251 : ℝ))
      h6 h8 (by norm_num)
  have h10 := rom_iv_add (L := (-0.4752622906211935867546 : ℝ)) (U := (-0.4752622906211935864499 :
      ℝ)) h9 h1 (by norm_num)
  have h11 := rom_iv_add (L := (1.0247377093788064132454 : ℝ)) (U := (1.0247377093788064135501 : ℝ))
      h10 (rom_iv_self (3 / 2 : ℝ)) (by norm_num)
  have h12 := rom_iv_mul_nn (L := (0.040136253931141335664 : ℝ)) (U := (0.0401362539311413362902 :
      ℝ)) hs h11 (by norm_num)
  have h13 := rom_iv_sub (L := (-0.9998382434842694631217 : ℝ)) (U := (-0.9998382434842692615256 :
      ℝ)) h5 h12 (by norm_num)
  exact h13

theorem rom_U1_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_U1 φ θ c s C S p ∈ Icc (0.3754132797036250661658 : ℝ) (0.3754132797036252975271 : ℝ) := by
  have h1 := rom_K_z0 hθ hp
  have h2 := rom_iv_mul_nn (L := (0.00153486591267227904 : ℝ)) (U := (0.00153486591267227904 : ℝ))
      hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038371647816806976 : ℝ)) (U := (0.00038371647816806976 : ℝ)) h2
      (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.49484596240559187844 : ℝ)) (U := (-0.494845962405591878435 : ℝ))
      h1 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.4944662498767774869716 : ℝ)) (U := (-0.4944662498767774188533 :
      ℝ)) hc h4 (by norm_num)
  have h6 := rom_iv_neg (L := (0.4944662498767774188533 : ℝ)) (U := (0.4944662498767774869716 : ℝ))
      h5 (by norm_num)
  have h7 := rom_iv_div (L := (0.0195886824 : ℝ)) (U := (0.0195886824 : ℝ)) hφ (k := 2)
      (by norm_num)
  have h8 := rom_iv_sub (L := (-0.9804113176 : ℝ)) (U := (-0.9804113176 : ℝ)) h7 (rom_iv_self
      (1 : ℝ)) (by norm_num)
  have h9 := rom_iv_mul (L := (-0.0384001069151757451366 : ℝ)) (U := (-0.0384001069151757445489 :
      ℝ)) hs h8 (by norm_num)
  have h10 := rom_iv_add (L := (0.4560661429616016737167 : ℝ)) (U := (0.4560661429616017424227 : ℝ))
      h6 h9 (by norm_num)
  have h11 := rom_iv_mul_nn (L := (2.3302610411251512953694 : ℝ)) (U := (2.3302610411251516043502 :
      ℝ)) (rom_iv_self (3 : ℝ)) hC (by norm_num)
  have h12 := rom_iv_div (L := (1.1651305205625756476847 : ℝ)) (U := (1.1651305205625758021751 : ℝ))
      h11 (k := 2) (by norm_num)
  have h13 := rom_iv_add (L := (1.6211966635241773214014 : ℝ)) (U := (1.6211966635241775445978 : ℝ))
      h10 h12 (by norm_num)
  have h14 := rom_iv_mul_nn (L := (2.0439045282 : ℝ)) (U := (2.0439045282 : ℝ)) (rom_iv_self
      (3 : ℝ)) hθ (by norm_num)
  have h15 := rom_iv_div (L := (1.0219522641 : ℝ)) (U := (1.0219522641 : ℝ)) h14 (k := 2)
      (by norm_num)
  have h16 := rom_iv_sub (L := (-1.9780477359 : ℝ)) (U := (-1.9780477359 : ℝ)) h15 (rom_iv_self
      (3 : ℝ)) (by norm_num)
  have h17 := rom_iv_mul (L := (-1.2457833838205522552356 : ℝ)) (U := (-1.2457833838205522470707 :
      ℝ)) hS h16 (by norm_num)
  have h18 := rom_iv_add (L := (0.3754132797036250661658 : ℝ)) (U := (0.3754132797036252975271 : ℝ))
      h13 h17 (by norm_num)
  exact h18

theorem rom_V1_z0 {φ θ c s S : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ)) :
    rom_V1 φ θ c s S ∈ Icc (0.7115158791101645080006 : ℝ) (0.7115158791101648846591 : ℝ) := by
  have h1 := rom_iv_add (L := (2.6813015094 : ℝ)) (U := (2.6813015094 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h2 := rom_iv_sub (L := (2.6421241446 : ℝ)) (U := (2.6421241446 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (2.6400967507914080802156 : ℝ)) (U := (2.6400967507914084438917 :
      ℝ)) hc h2 (by norm_num)
  have h4 := rom_iv_sub (L := (2.6009294072226114962455 : ℝ)) (U := (2.6009294072226118605209 : ℝ))
      h3 hs (by norm_num)
  have h5 := rom_iv_mul_nn (L := (1.8894135281124469758618 : ℝ)) (U := (1.8894135281124469882449 :
      ℝ)) (rom_iv_self (3 : ℝ)) hS (by norm_num)
  have h6 := rom_iv_sub (L := (0.7115158791101645080006 : ℝ)) (U := (0.7115158791101648846591 : ℝ))
      h4 h5 (by norm_num)
  exact h6

theorem rom_U2_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_U2 φ θ c s C S p ∈ Icc (0.1719866080737490478203 : ℝ) (0.1719866080737492530389 : ℝ) := by
  have h1 := rom_K_z0 hθ hp
  have h2 := rom_iv_mul_nn (L := (0.00153486591267227904 : ℝ)) (U := (0.00153486591267227904 : ℝ))
      hφ hφ (by norm_num)
  have h3 := rom_iv_div (L := (0.00038371647816806976 : ℝ)) (U := (0.00038371647816806976 : ℝ)) h2
      (k := 4) (by norm_num)
  have h4 := rom_iv_sub (L := (-0.49484596240559187844 : ℝ)) (U := (-0.494845962405591878435 : ℝ))
      h1 h3 (by norm_num)
  have h5 := rom_iv_mul (L := (-0.0193818018231716152286 : ℝ)) (U := (-0.0193818018231716149318 :
      ℝ)) hs h4 (by norm_num)
  have h6 := rom_iv_neg (L := (0.0193818018231716149318 : ℝ)) (U := (0.0193818018231716152286 : ℝ))
      h5 (by norm_num)
  have h7 := rom_iv_div (L := (0.0195886824 : ℝ)) (U := (0.0195886824 : ℝ)) hφ (k := 2)
      (by norm_num)
  have h8 := rom_iv_sub (L := (-0.9804113176 : ℝ)) (U := (-0.9804113176 : ℝ)) h7 (rom_iv_self
      (1 : ℝ)) (by norm_num)
  have h9 := rom_iv_mul (L := (-0.9796590138752723902706 : ℝ)) (U := (-0.9796590138752722553215 :
      ℝ)) hc h8 (by norm_num)
  have h10 := rom_iv_sub (L := (0.9990408156984438702533 : ℝ)) (U := (0.9990408156984440054992 : ℝ))
      h6 h9 (by norm_num)
  have h11 := rom_iv_div (L := (0.3149022546854078293103 : ℝ)) (U := (0.3149022546854078313742 : ℝ))
      hS (k := 2) (by norm_num)
  have h12 := rom_iv_sub (L := (0.6841385610130360388791 : ℝ)) (U := (0.6841385610130361761889 : ℝ))
      h10 h11 (by norm_num)
  have h13 := rom_iv_div (L := (0.3406507547 : ℝ)) (U := (0.3406507547 : ℝ)) hθ (k := 2)
      (by norm_num)
  have h14 := rom_iv_sub (L := (-0.6593492453 : ℝ)) (U := (-0.6593492453 : ℝ)) h13 (rom_iv_self
      (1 : ℝ)) (by norm_num)
  have h15 := rom_iv_mul (L := (-0.5121519529392869910588 : ℝ)) (U := (-0.51215195293928692315 : ℝ))
      hC h14 (by norm_num)
  have h16 := rom_iv_add (L := (0.1719866080737490478203 : ℝ)) (U := (0.1719866080737492530389 : ℝ))
      h12 h15 (by norm_num)
  exact h16

theorem rom_V2_z0 {φ θ c s C : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ)) :
    rom_V2 φ θ c s C ∈ Icc (0.3259639689454426970937 : ℝ) (0.3259639689454429393162 : ℝ) := by
  have h1 := rom_iv_add (L := (2.6813015094 : ℝ)) (U := (2.6813015094 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h2 := rom_iv_sub (L := (2.6421241446 : ℝ)) (U := (2.6421241446 : ℝ)) h1 hφ (by norm_num)
  have h3 := rom_iv_mul_nn (L := (0.1034849841229609840899 : ℝ)) (U := (0.1034849841229609856735 :
      ℝ)) hs h2 (by norm_num)
  have h4 := rom_iv_add (L := (1.1027176493204932318771 : ℝ)) (U := (1.102717649320493371106 : ℝ))
      h3 hc (by norm_num)
  have h5 := rom_iv_sub (L := (0.3259639689454426970937 : ℝ)) (U := (0.3259639689454429393162 : ℝ))
      h4 hC (by norm_num)
  exact h5

theorem rom_H1_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_H1 φ θ c s C S p ∈ Icc (-0.0000000000127515980892 : ℝ) (-0.0000000000127505356853 : ℝ) := by
  have h1 := rom_D_z0 hφ hθ hc hs
  have h2 := rom_Nb_z0 hφ hθ hc hs hp
  have h3 := rom_U1_z0 hφ hθ hc hs hC hS hp
  have h4 := rom_V1_z0 hφ hθ hc hs hS
  have h5 := rom_iv_mul_nn (L := (0.7114007867679214764079 : ℝ)) (U := (0.7114007867679220187753 :
      ℝ)) h1 h3 (by norm_num)
  have h6 := rom_iv_mul (L := (-0.7114007867806730744971 : ℝ)) (U := (-0.7114007867806725544606 :
      ℝ)) h2 h4 (by norm_num)
  have h7 := rom_iv_add (L := (-0.0000000000127515980892 : ℝ)) (U := (-0.0000000000127505356853 :
      ℝ)) h5 h6 (by norm_num)
  exact h7

theorem rom_H2_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_H2 φ θ c s C S p ∈ Icc (-0.0000000000278151036724 : ℝ) (-0.0000000000278143592721 : ℝ) := by
  have h1 := rom_D_z0 hφ hθ hc hs
  have h2 := rom_Nb_z0 hφ hθ hc hs hp
  have h3 := rom_U2_z0 hφ hθ hc hs hC hS hp
  have h4 := rom_V2_z0 hφ hθ hc hs hC
  have h5 := rom_iv_mul_nn (L := (0.3259112421217575238685 : ℝ)) (U := (0.3259112421217579603724 :
      ℝ)) h1 h3 (by norm_num)
  have h6 := rom_iv_mul (L := (-0.3259112421495726275409 : ℝ)) (U := (-0.3259112421495723196445 :
      ℝ)) h2 h4 (by norm_num)
  have h7 := rom_iv_add (L := (-0.0000000000278151036724 : ℝ)) (U := (-0.0000000000278143592721 :
      ℝ)) h5 h6 (by norm_num)
  exact h7

theorem rom_MH1_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_MH1 φ θ c s C S p ∈ Icc (-0.000000000009915950597 : ℝ) (-0.0000000000099155784208 : ℝ) := by
  have h1 := rom_H1_z0 hφ hθ hc hs hC hS hp
  have h2 := rom_H2_z0 hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-0.0000000000018885116771 : ℝ)) (U := (-0.0000000000018883543349 :
      ℝ)) (rom_iv_self (0.1481 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul (L := (-0.0000000000080274389199 : ℝ)) (U := (-0.0000000000080272240859 :
      ℝ)) (rom_iv_self (0.2886 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_add (L := (-0.000000000009915950597 : ℝ)) (U := (-0.0000000000099155784208 : ℝ))
      h3 h4 (by norm_num)
  exact h5

theorem rom_MH2_z0 {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773648 : ℝ) (0.0391773648 : ℝ))
    (hθ : θ ∈ Icc (0.6813015094 : ℝ) (0.6813015094 : ℝ))
    (hc : c ∈ Icc (0.9992326651975322477872 : ℝ) (0.9992326651975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673435687965833708 : ℝ) (0.0391673435687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536803750504317898 : ℝ) (0.7767536803750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045093708156586206 : ℝ) (0.6298045093708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_MH2 φ θ c s C S p ∈ Icc (-0.0000000000172760407234 : ℝ) (-0.0000000000172726825567 : ℝ) :=
        by
  have h1 := rom_H1_z0 hφ hθ hc hs hC hS hp
  have h2 := rom_H2_z0 hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-0.0000000000347072996792 : ℝ)) (U := (-0.0000000000347044080282 :
      ℝ)) (rom_iv_self (2.7218 : ℝ)) h1 (by norm_num)
  have h4 := rom_iv_mul (L := (-0.0000000000174317254715 : ℝ)) (U := (-0.0000000000174312589558 :
      ℝ)) (rom_iv_self (0.6267 : ℝ)) h2 (by norm_num)
  have h5 := rom_iv_sub (L := (-0.0000000000172760407234 : ℝ)) (U := (-0.0000000000172726825567 :
      ℝ)) h3 h4 (by norm_num)
  exact h5

/-! ### Enclosures near `(φ₀, θ₀)` -/

theorem rom_K_tiny {θ p : ℝ}
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_K θ p ∈ Icc (-0.494462246061489 : ℝ) (-0.4944622457933586 : ℝ) := by
  have h1 := rom_iv_div (L := (1.5707963267948966 : ℝ)) (U := (1.5707963267948967 : ℝ)) hp (k := 2)
      (by norm_num)
  have h2 := rom_iv_sub (L := (0.0707963267948966 : ℝ)) (U := (0.0707963267948967 : ℝ)) h1
      (rom_iv_self (3 / 2 : ℝ)) (by norm_num)
  have h3 := rom_iv_sub (L := (-0.6105051827051034 : ℝ)) (U := (-0.6105051825051033 : ℝ)) h2 hθ
      (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.4641717465744579 : ℝ)) (U := (0.4641717468469786 : ℝ)) hθ hθ
      (by norm_num)
  have h5 := rom_iv_div (L := (0.1160429366436144 : ℝ)) (U := (0.1160429367117447 : ℝ)) h4 (k := 4)
      (by norm_num)
  have h6 := rom_iv_add (L := (-0.494462246061489 : ℝ)) (U := (-0.4944622457933586 : ℝ)) h3 h5
      (by norm_num)
  exact h6

theorem rom_D_tiny {φ θ c s : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ)) :
    rom_D φ θ c s ∈ Icc (1.8949803458000575 : ℝ) (1.8949803467441497 : ℝ) := by
  have h1 := rom_iv_mul_nn (L := (1.9984653301950644 : ℝ)) (U := (1.9984653305950648 : ℝ))
      (rom_iv_self (2 : ℝ)) hc (by norm_num)
  have h2 := rom_iv_add (L := (2.6813015093 : ℝ)) (U := (2.6813015095 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h3 := rom_iv_sub (L := (2.6421241444 : ℝ)) (U := (2.6421241448 : ℝ)) h2 hφ (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.1034849838509151 : ℝ)) (U := (0.1034849843950069 : ℝ)) h3 hs
      (by norm_num)
  have h5 := rom_iv_sub (L := (1.8949803458000575 : ℝ)) (U := (1.8949803467441497 : ℝ)) h1 h4
      (by norm_num)
  exact h5

theorem rom_β₀_tiny {φ c : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ)) :
    rom_β₀ φ c ∈ Icc (-0.4802194839743831 : ℝ) (-0.480219483824383 : ℝ) := by
  have h1 := rom_iv_sub (L := (-0.4608226353 : ℝ)) (U := (-0.4608226351 : ℝ)) hφ (rom_iv_self
      (1 / 2 : ℝ)) (by norm_num)
  have h2 := rom_iv_div (L := (0.4996163325487661 : ℝ)) (U := (0.4996163326487662 : ℝ)) hc (k := 2)
      (by norm_num)
  have h3 := rom_iv_sub (L := (-0.9604389679487662 : ℝ)) (U := (-0.9604389676487661 : ℝ)) h1 h2
      (by norm_num)
  have h4 := rom_iv_div (L := (-0.4802194839743831 : ℝ)) (U := (-0.480219483824383 : ℝ)) h3 (k := 2)
      (by norm_num)
  exact h4

theorem rom_N_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_N φ θ c s p ∈ Icc (2.2935372020164897 : ℝ) (2.2935372029769448 : ℝ) := by
  have h1 := rom_K_tiny hθ hp
  have h2 := rom_β₀_tiny hφ hc
  have h3 := rom_iv_div (L := (0.0195836717343982 : ℝ)) (U := (0.0195836718343983 : ℝ)) hs (k := 2)
      (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.0015348659048368 : ℝ)) (U := (0.0015348659205078 : ℝ)) hφ hφ
      (by norm_num)
  have h5 := rom_iv_div (L := (0.0003837164762092 : ℝ)) (U := (0.000383716480127 : ℝ)) h4 (k := 4)
      (by norm_num)
  have h6 := rom_iv_sub (L := (0.0191999552542712 : ℝ)) (U := (0.0191999553581891 : ℝ)) h3 h5
      (by norm_num)
  have h7 := rom_iv_add (L := (-0.4752622908072178 : ℝ)) (U := (-0.4752622904351695 : ℝ)) h6 h1
      (by norm_num)
  have h8 := rom_iv_add (L := (1.0247377091927822 : ℝ)) (U := (1.0247377095648305 : ℝ)) h7
      (rom_iv_self (3 / 2 : ℝ)) (by norm_num)
  have h9 := rom_iv_add (L := (2.6813015093 : ℝ)) (U := (2.6813015095 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h10 := rom_iv_sub (L := (2.6421241444 : ℝ)) (U := (2.6421241448 : ℝ)) h9 hφ (by norm_num)
  have h11 := rom_iv_mul (L := (-1.2687994934121143 : ℝ)) (U := (-1.2687994928237075 : ℝ)) h10 h2
      (by norm_num)
  have h12 := rom_iv_sub (L := (2.2935372020164897 : ℝ)) (U := (2.2935372029769448 : ℝ)) h8 h11
      (by norm_num)
  exact h12

theorem rom_a₁_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_a₁ φ θ c s p ∈ Icc (1.2103224215264914 : ℝ) (1.2103224226363242 : ℝ) := by
  have h1 := rom_D_tiny hφ hθ hc hs
  have h2 := rom_N_tiny hφ hθ hc hs hp
  have h3 := rom_iv_div2 (L := (1.2103224215264914 : ℝ)) (U := (1.2103224226363242 : ℝ)) h2 h1
      (by norm_num)
  exact h3

theorem rom_b₁_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_b₁ φ θ c s p ∈ Icc (-0.5276245982518305 : ℝ) (-0.5276245978162966 : ℝ) := by
  have h1 := rom_a₁_tiny hφ hθ hc hs hp
  have h2 := rom_β₀_tiny hφ hc
  have h3 := rom_iv_mul_nn (L := (0.0474051139919136 : ℝ)) (U := (0.0474051142774474 : ℝ)) hs h1
      (by norm_num)
  have h4 := rom_iv_sub (L := (-0.5276245982518305 : ℝ)) (U := (-0.5276245978162966 : ℝ)) h2 h3
      (by norm_num)
  exact h4

theorem rom_b₂_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_b₂ φ θ c s p ∈ Icc (0.9202583844071525 : ℝ) (0.9202583859486056 : ℝ) := by
  have h1 := rom_K_tiny hθ hp
  have h2 := rom_b₁_tiny hφ hθ hc hs hp
  have h3 := rom_iv_add (L := (2.6813015093 : ℝ)) (U := (2.6813015095 : ℝ)) (rom_iv_self (2 : ℝ)) hθ
      (by norm_num)
  have h4 := rom_iv_mul (L := (-1.4147206317419642 : ℝ)) (U := (-1.4147206304686415 : ℝ)) h3 h2
      (by norm_num)
  have h5 := rom_iv_sub (L := (0.9202583844071525 : ℝ)) (U := (0.9202583859486056 : ℝ)) h1 h4
      (by norm_num)
  exact h5

theorem rom_c₁_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_c₁ φ θ c s p ∈ Icc (0.6260455224274898 : ℝ) (0.6260455232985577 : ℝ) := by
  have h1 := rom_b₁_tiny hφ hθ hc hs hp
  have h2 := rom_iv_div (L := (1.5707963267948966 : ℝ)) (U := (1.5707963267948967 : ℝ)) hp (k := 2)
      (by norm_num)
  have h3 := rom_iv_sub (L := (-0.4292036732051034 : ℝ)) (U := (-0.4292036732051033 : ℝ)) h2
      (rom_iv_self (2 : ℝ)) (by norm_num)
  have h4 := rom_iv_mul (L := (-1.055249196503661 : ℝ)) (U := (-1.0552491956325932 : ℝ))
      (rom_iv_self (2 : ℝ)) h1 (by norm_num)
  have h5 := rom_iv_sub (L := (0.6260455224274898 : ℝ)) (U := (0.6260455232985577 : ℝ)) h3 h4
      (by norm_num)
  exact h5

theorem rom_Δ₁_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_Δ₁ φ θ c s p ∈ Icc (-0.699601865207041 : ℝ) (-0.699601862138036 : ℝ) := by
  have h1 := rom_a₁_tiny hφ hθ hc hs hp
  have h2 := rom_b₁_tiny hφ hθ hc hs hp
  have h3 := rom_b₂_tiny hφ hθ hc hs hp
  have h4 := rom_iv_mul_nn (L := (1.2093936988892148 : ℝ)) (U := (1.2093937002402607 : ℝ)) h1 hc
      (by norm_num)
  have h5 := rom_iv_div (L := (0.0097918358671991 : ℝ)) (U := (0.0097918359171992 : ℝ)) hs (k := 4)
      (by norm_num)
  have h6 := rom_iv_sub (L := (1.1996018629720156 : ℝ)) (U := (1.1996018643730616 : ℝ)) h4 h5
      (by norm_num)
  have h7 := rom_iv_sub (L := (0.1996018629720156 : ℝ)) (U := (0.1996018643730616 : ℝ)) h6
      (rom_iv_self (1 : ℝ)) (by norm_num)
  have h8 := rom_iv_mul_nn (L := (0.0015348659048368 : ℝ)) (U := (0.0015348659205078 : ℝ)) hφ hφ
      (by norm_num)
  have h9 := rom_iv_div (L := (0.0003837164762092 : ℝ)) (U := (0.000383716480127 : ℝ)) h8 (k := 4)
      (by norm_num)
  have h10 := rom_iv_neg (L := (-0.000383716480127 : ℝ)) (U := (-0.0003837164762092 : ℝ)) h9
      (by norm_num)
  have h11 := rom_iv_mul (L := (-0.0206709414159279 : ℝ)) (U := (-0.0206709412933398 : ℝ)) h2 hφ
      (by norm_num)
  have h12 := rom_iv_add (L := (-0.0210546578960549 : ℝ)) (U := (-0.021054657769549 : ℝ)) h10 h11
      (by norm_num)
  have h13 := rom_iv_add (L := (0.8992037265110976 : ℝ)) (U := (0.8992037281790566 : ℝ)) h12 h3
      (by norm_num)
  have h14 := rom_iv_sub (L := (-0.699601865207041 : ℝ)) (U := (-0.699601862138036 : ℝ)) h7 h13
      (by norm_num)
  exact h14

theorem rom_Δ₂_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_Δ₂ φ θ c s p ∈ Icc (0.2499999995644661 : ℝ) (0.2500000004355339 : ℝ) := by
  have h1 := rom_a₁_tiny hφ hθ hc hs hp
  have h2 := rom_b₁_tiny hφ hθ hc hs hp
  have h3 := rom_iv_div (L := (0.249808166274383 : ℝ)) (U := (0.2498081663243831 : ℝ)) hc (k := 4)
      (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.0474051139919136 : ℝ)) (U := (0.0474051142774474 : ℝ)) h1 hs
      (by norm_num)
  have h5 := rom_iv_add (L := (0.2972132802662966 : ℝ)) (U := (0.2972132806018305 : ℝ)) h3 h4
      (by norm_num)
  have h6 := rom_iv_sub (L := (-0.2027867197337034 : ℝ)) (U := (-0.2027867193981695 : ℝ)) h5
      (rom_iv_self (1 / 2 : ℝ)) (by norm_num)
  have h7 := rom_iv_div (L := (0.01958868235 : ℝ)) (U := (0.01958868245 : ℝ)) hφ (k := 2)
      (by norm_num)
  have h8 := rom_iv_sub (L := (0.5472132801662966 : ℝ)) (U := (0.5472132807018305 : ℝ)) h7 h2
      (by norm_num)
  have h9 := rom_iv_sub (L := (-0.4527867198337034 : ℝ)) (U := (-0.4527867192981695 : ℝ)) h8
      (rom_iv_self (1 : ℝ)) (by norm_num)
  have h10 := rom_iv_sub (L := (0.2499999995644661 : ℝ)) (U := (0.2500000004355339 : ℝ)) h6 h9
      (by norm_num)
  exact h10

theorem rom_κ₂₁_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₂₁ φ θ c s p ∈ Icc (-0.9191792949885387 : ℝ) (-0.9191792905880178 : ℝ) := by
  have h1 := rom_a₁_tiny hφ hθ hc hs hp
  have h2 := rom_Δ₁_tiny hφ hθ hc hs hp
  have h3 := rom_Δ₂_tiny hφ hθ hc hs hp
  have h4 := rom_iv_mul (L := (-0.6990650364179566 : ℝ)) (U := (-0.699065033211386 : ℝ)) hc h2
      (by norm_num)
  have h5 := rom_iv_mul_nn (L := (0.0097918358501404 : ℝ)) (U := (0.0097918359342579 : ℝ)) hs h3
      (by norm_num)
  have h6 := rom_iv_sub (L := (-0.7088568723522145 : ℝ)) (U := (-0.7088568690615264 : ℝ)) h4 h5
      (by norm_num)
  have h7 := rom_iv_sub (L := (-0.2103224226363242 : ℝ)) (U := (-0.2103224215264914 : ℝ))
      (rom_iv_self (1 : ℝ)) h1 (by norm_num)
  have h8 := rom_iv_add (L := (-0.9191792949885387 : ℝ)) (U := (-0.9191792905880178 : ℝ)) h6 h7
      (by norm_num)
  exact h8

theorem rom_κ₂₂_tiny {φ θ c s p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₂₂ φ θ c s p ∈ Icc (0.472406619153288 : ℝ) (0.4724066203338127 : ℝ) := by
  have h1 := rom_Δ₁_tiny hφ hθ hc hs hp
  have h2 := rom_Δ₂_tiny hφ hθ hc hs hp
  have h3 := rom_iv_mul (L := (-0.0274015466858953 : ℝ)) (U := (-0.0274015464257701 : ℝ)) hs h1
      (by norm_num)
  have h4 := rom_iv_mul_nn (L := (0.2498081658391833 : ℝ)) (U := (0.2498081667595828 : ℝ)) hc h2
      (by norm_num)
  have h5 := rom_iv_add (L := (0.222406619153288 : ℝ)) (U := (0.2224066203338127 : ℝ)) h3 h4
      (by norm_num)
  have h6 := rom_iv_add (L := (0.472406619153288 : ℝ)) (U := (0.4724066203338127 : ℝ)) h5
      (rom_iv_self (1 / 4 : ℝ)) (by norm_num)
  exact h6

theorem rom_κ₃₁_tiny {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536802750504317898 : ℝ) (0.7767536804750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045092708156586206 : ℝ) (0.6298045094708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₃₁ φ θ c s C S p ∈ Icc (-0.6137632318761937 : ℝ) (-0.613763227012046 : ℝ) := by
  have h1 := rom_b₁_tiny hφ hθ hc hs hp
  have h2 := rom_κ₂₁_tiny hφ hθ hc hs hp
  have h3 := rom_iv_div (L := (0.3883768401375252 : ℝ)) (U := (0.3883768402375253 : ℝ)) hC (k := 2)
      (by norm_num)
  have h4 := rom_iv_add (L := (0.4723754017481695 : ℝ)) (U := (0.4723754021837034 : ℝ)) (rom_iv_self
      (1 : ℝ)) h1 (by norm_num)
  have h5 := rom_iv_div (L := (0.34065075465 : ℝ)) (U := (0.34065075475 : ℝ)) hθ (k := 2)
      (by norm_num)
  have h6 := rom_iv_sub (L := (0.1317246469981695 : ℝ)) (U := (0.1317246475337034 : ℝ)) h4 h5
      (by norm_num)
  have h7 := rom_iv_mul_nn (L := (0.0829607766615535 : ℝ)) (U := (0.0829607770251802 : ℝ)) hS h6
      (by norm_num)
  have h8 := rom_iv_sub (L := (0.305416063112345 : ℝ)) (U := (0.3054160635759718 : ℝ)) h3 h7
      (by norm_num)
  have h9 := rom_iv_add (L := (-0.6137632318761937 : ℝ)) (U := (-0.613763227012046 : ℝ)) h8 h2
      (by norm_num)
  exact h9

theorem rom_κ₃₂_tiny {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536802750504317898 : ℝ) (0.7767536804750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045092708156586206 : ℝ) (0.6298045094708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₃₂ φ θ c s C S p ∈ Icc (0.8896264781274558 : ℝ) (0.8896264798503036 : ℝ) := by
  have h1 := rom_b₁_tiny hφ hθ hc hs hp
  have h2 := rom_κ₂₂_tiny hφ hθ hc hs hp
  have h3 := rom_iv_div (L := (0.3149022546354078 : ℝ)) (U := (0.3149022547354079 : ℝ)) hS (k := 2)
      (by norm_num)
  have h4 := rom_iv_add (L := (0.4723754017481695 : ℝ)) (U := (0.4723754021837034 : ℝ)) (rom_iv_self
      (1 : ℝ)) h1 (by norm_num)
  have h5 := rom_iv_div (L := (0.34065075465 : ℝ)) (U := (0.34065075475 : ℝ)) hθ (k := 2)
      (by norm_num)
  have h6 := rom_iv_sub (L := (0.1317246469981695 : ℝ)) (U := (0.1317246475337034 : ℝ)) h4 h5
      (by norm_num)
  have h7 := rom_iv_mul_nn (L := (0.10231760433876 : ℝ)) (U := (0.102317604781083 : ℝ)) hC h6
      (by norm_num)
  have h8 := rom_iv_add (L := (0.4172198589741678 : ℝ)) (U := (0.4172198595164909 : ℝ)) h3 h7
      (by norm_num)
  have h9 := rom_iv_add (L := (0.8896264781274558 : ℝ)) (U := (0.8896264798503036 : ℝ)) h8 h2
      (by norm_num)
  exact h9

theorem rom_κ₄₁_tiny {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536802750504317898 : ℝ) (0.7767536804750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045092708156586206 : ℝ) (0.6298045094708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₄₁ φ θ c s C S p ∈ Icc (-0.3083471731643696 : ℝ) (-0.3083471590355533 : ℝ) := by
  have h1 := rom_κ₂₁_tiny hφ hθ hc hs hp
  have h2 := rom_κ₃₁_tiny hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-1.2275264637523874 : ℝ)) (U := (-1.227526454024092 : ℝ))
      (rom_iv_self (2 : ℝ)) h2 (by norm_num)
  have h4 := rom_iv_sub (L := (-0.3083471731643696 : ℝ)) (U := (-0.3083471590355533 : ℝ)) h3 h1
      (by norm_num)
  exact h4

theorem rom_κ₅₁_tiny {φ θ c s C S p : ℝ}
    (hφ : φ ∈ Icc (0.0391773647 : ℝ) (0.0391773649 : ℝ))
    (hθ : θ ∈ Icc (0.6813015093 : ℝ) (0.6813015095 : ℝ))
    (hc : c ∈ Icc (0.9992326650975322477872 : ℝ) (0.9992326652975323854325 : ℝ))
    (hs : s ∈ Icc (0.0391673434687965833708 : ℝ) (0.0391673436687965839701 : ℝ))
    (hC : C ∈ Icc (0.7767536802750504317898 : ℝ) (0.7767536804750505347834 : ℝ))
    (hS : S ∈ Icc (0.6298045092708156586206 : ℝ) (0.6298045094708156627483 : ℝ))
    (hp : p ∈ Icc (3.14159265358979323846 : ℝ) (3.14159265358979323847 : ℝ)) :
    rom_κ₅₁ φ θ c s C S p ∈ Icc (-1.017204042225896 : ℝ) (-1.0172040313877678 : ℝ) := by
  have h1 := rom_a₁_tiny hφ hθ hc hs hp
  have h2 := rom_κ₃₁_tiny hφ hθ hc hs hC hS hp
  have h3 := rom_iv_mul (L := (-1.2275264637523874 : ℝ)) (U := (-1.227526454024092 : ℝ))
      (rom_iv_self (2 : ℝ)) h2 (by norm_num)
  have h4 := rom_iv_sub (L := (-2.2275264637523874 : ℝ)) (U := (-2.227526454024092 : ℝ)) h3
      (rom_iv_self (1 : ℝ)) (by norm_num)
  have h5 := rom_iv_add (L := (-1.017204042225896 : ℝ)) (U := (-1.0172040313877678 : ℝ)) h4 h1
      (by norm_num)
  exact h5


end MovingSofa
