module

public import MovingSofaStability.AngularFaceStability
public import MovingSofaStability.ArcAtoms
public import MovingSofaStability.BaekDeficit
public import MovingSofaStability.CBVAlgebra
public import MovingSofaStability.CanonicalContacts
public import MovingSofaStability.CanonicalTriple
public import MovingSofaStability.CapCoercivity
public import MovingSofaStability.CapDistance
public import MovingSofaStability.CapShape
public import MovingSofaStability.CapWidthGeometry
public import MovingSofaStability.CompactSetLimits
public import MovingSofaStability.ConvexParallelArea
public import MovingSofaStability.CoreAreaBound
public import MovingSofaStability.CoreGraph
public import MovingSofaStability.CoreIntegral
public import MovingSofaStability.CoreMonotonicity
public import MovingSofaStability.CoreRegionGeometry
public import MovingSofaStability.CornerAnalysis
public import MovingSofaStability.CurveRoof
public import MovingSofaStability.CutSeparation
public import MovingSofaStability.EnvelopeSlack
public import MovingSofaStability.EnvelopeSlope
public import MovingSofaStability.EpigraphBalls
public import MovingSofaStability.EuclideanDisks
public import MovingSofaStability.EuclideanGeometry
public import MovingSofaStability.ExposedFaceStability
public import MovingSofaStability.FloorCoverage
public import MovingSofaStability.FourArcCoercivity
public import MovingSofaStability.GerverMargins
public import MovingSofaStability.GerverRoof
public import MovingSofaStability.GlobalStability
public import MovingSofaStability.GreenNorm
public import MovingSofaStability.IntegralEstimates
public import MovingSofaStability.InteriorBalls
public import MovingSofaStability.LocalArmMargins
public import MovingSofaStability.LocalSofaRecovery
public import MovingSofaStability.LocalUpperBound
public import MovingSofaStability.MamikonEnergy
public import MovingSofaStability.MissingAreaRecovery
public import MovingSofaStability.MixedArea
public import MovingSofaStability.NicheContainment
public import MovingSofaStability.NicheFeet
public import MovingSofaStability.NonsmoothAffinity
public import MovingSofaStability.NonsmoothBookkeeping
public import MovingSofaStability.ODEReconstruction
public import MovingSofaStability.OmittedWedgeArea
public import MovingSofaStability.PartialHallways
public import MovingSofaStability.PunctureMetric
public import MovingSofaStability.PunctureTopology
public import MovingSofaStability.PuncturedSofa
public import MovingSofaStability.QuadraticDeficit
public import MovingSofaStability.QualitativeEntry
public import MovingSofaStability.ReferenceCoreVariation
public import MovingSofaStability.ResidualIntegrability
public import MovingSofaStability.ResidualMass
public import MovingSofaStability.ResidualPropagation
public import MovingSofaStability.Residuals
public import MovingSofaStability.RigidInterior
public import MovingSofaStability.RoofGeometry
public import MovingSofaStability.RoofMargins
public import MovingSofaStability.SeparatedWedges
public import MovingSofaStability.SharpCapDistance
public import MovingSofaStability.SharpEvaluation
public import MovingSofaStability.SharpExponent
public import MovingSofaStability.SharpIntegralControl
public import MovingSofaStability.SharpKernelNorms
public import MovingSofaStability.SharpReconstruction
public import MovingSofaStability.SofaBounds
public import MovingSofaStability.SofaCap
public import MovingSofaStability.SofaCoordinates
public import MovingSofaStability.SofaLimitMotion
public import MovingSofaStability.Statement
public import MovingSofaStability.SupportDistance
public import MovingSofaStability.SymmetricDifference
public import MovingSofaStability.TerminalBookkeeping
public import MovingSofaStability.TerminalComparison
public import MovingSofaStability.TerminalFloor
public import MovingSofaStability.TrigKernelIntegrals
public import MovingSofaStability.UniformGeometryBounds
public import MovingSofaStability.WideConcavity
public import MovingSofaStability.WideDomain
public import MovingSofaStability.WideFirstVariation
public import MovingSofaStability.WideGerverCertificate
public import MovingSofaStability.WideResidualEnergy

/-!
# Stability: intended source assembly and sharpness additions

GlobalStability.lean contains the intended unrestricted and terminal-angle
proofs. SharpCapDistance.lean supplies stronger cap theorems with coefficient
2 / cos(phi), uniformly less than 2.002 in the source box. The older coefficient
80 declarations remain available, and the global constants remain existential.

SharpExponent.lean supplies the punctured Gerver family and rules out every
Hausdorff exponent greater than one half, including arbitrary rigid alignment.
It does not claim sharpness for symmetric-difference area or feasible-cap constants.

IMPORTANT: none of this development has been compiled or kernel-checked.
These files are proof source, not verified formalization. No Lean, Lake, CI,
remote build, or TeX compilation was run. Formula tests check analytic formulas
only; they do not establish elaboration or theorem dependencies.

See docs/stability/SHARPNESS_HANDOFF.md for the new entry points and limitations.
-/
