from drive import *

all_defs = ['rom_K', 'rom_Kθ', 'rom_D', 'rom_Nb', 'rom_U1', 'rom_V1', 'rom_U2', 'rom_V2', 'rom_H1', 'rom_H2',
            'rom_Dφ', 'rom_Dθ', 'rom_Nbφ', 'rom_Nbθ', 'rom_U1φ', 'rom_U1θ', 'rom_V1φ', 'rom_V1θ',
            'rom_U2φ', 'rom_U2θ', 'rom_V2φ', 'rom_V2θ', 'rom_H1φ', 'rom_H1θ', 'rom_H2φ', 'rom_H2θ',
            'rom_G1', 'rom_G2', 'rom_G1φ', 'rom_G1θ', 'rom_G2φ', 'rom_G2θ', 'rom_MH1', 'rom_MH2',
            'rom_β₀', 'rom_N', 'rom_a₁', 'rom_b₁', 'rom_b₂', 'rom_c₁', 'rom_Δ₁', 'rom_Δ₂',
            'rom_κ₂₁', 'rom_κ₂₂', 'rom_κ₃₁', 'rom_κ₃₂', 'rom_κ₄₁', 'rom_κ₅₁']
deriv_bases = ['rom_K', 'rom_D', 'rom_Nb', 'rom_U1', 'rom_V1', 'rom_U2', 'rom_V2', 'rom_H1', 'rom_H2', 'rom_G1', 'rom_G2']
box_names = ['rom_K', 'rom_D', 'rom_Nb', 'rom_U1', 'rom_V1', 'rom_U2', 'rom_V2',
             'rom_Dφ', 'rom_Dθ', 'rom_Nbφ', 'rom_Nbθ', 'rom_U1φ', 'rom_U1θ', 'rom_V1φ', 'rom_V1θ',
             'rom_U2φ', 'rom_U2θ', 'rom_V2φ', 'rom_V2θ', 'rom_H1φ', 'rom_H1θ', 'rom_H2φ', 'rom_H2θ',
             'rom_G1φ', 'rom_G1θ', 'rom_G2φ', 'rom_G2θ']
z0_names = ['rom_K', 'rom_D', 'rom_Nb', 'rom_U1', 'rom_V1', 'rom_U2', 'rom_V2', 'rom_H1', 'rom_H2', 'rom_MH1', 'rom_MH2']
tiny_names = ['rom_K', 'rom_D', 'rom_β₀', 'rom_N', 'rom_a₁', 'rom_b₁', 'rom_b₂', 'rom_c₁', 'rom_Δ₁', 'rom_Δ₂',
              'rom_κ₂₁', 'rom_κ₂₂', 'rom_κ₃₁', 'rom_κ₃₂', 'rom_κ₄₁', 'rom_κ₅₁']

HEADER = '''module

public import MovingSofaOptimality.Basic.Interval
public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv

/-!
# The reduced system for the parameters of Gerver's sofa

This file is generated by `scripts/romik/mk_num.py`; every step is an explicit inequality checked by
`norm_num`. It defines, as polynomials in the "atoms"
`φ, θ, c = cos φ, s = sin φ, C = cos θ, S = sin θ, p = π`:

* the reduced system `H = (rom_H1, rom_H2)` whose zeros in the box are the angles `(φ, θ)` of the
  solutions of Romik's system (see `MovingSofaOptimality.External.Romik`), and its partial
  derivatives;
* the Newton-type map `G(z) = z - M H(z)` (`rom_G1`, `rom_G2`, with `M ≈ DH(z*)⁻¹`) and its partial
  derivatives;
* the linear parameters `a₁, b₁, b₂, c₁, κ_{j}` of a solution as functions of the atoms.

It proves the derivative formulas (`*_hasDerivAt_φ`, `*_hasDerivAt_θ`), and enclosures by interval
arithmetic (`MovingSofaOptimality.Basic.Interval`) in three regimes, from enclosures of the atoms
(`MovingSofaOptimality.External.Romik.Calc`):

* `_box`: for `(φ, θ) ∈ [0.039, 0.04] × [0.68, 0.69]` (bounds on the derivatives of `G`, which make
  `G` a contraction there);
* `_z0`: at `(φ₀, θ₀) = (0.0391773648, 0.6813015094)` (the residual `M H(φ₀, θ₀)` is below
  `2·10⁻¹¹`);
* `_tiny`: for `|φ - φ₀|, |θ - θ₀| ≤ 10⁻¹⁰` (enclosures of the parameters of the solution).
-/

@[expose] public section

open Real Set

namespace MovingSofaOptimality
'''

FOOTER = '''
end MovingSofaOptimality
'''

if __name__ == '__main__':
    out = [HEADER]
    out.append('/-! ### Definitions -/\n')
    out.append(gen_defs(all_defs))
    out.append('/-! ### Derivatives -/\n')
    out.append(gen_deriv(deriv_bases))
    out.append('/-! ### Enclosures on the box `[0.039, 0.04] × [0.68, 0.69]` -/\n')
    res, txt = gen_regime('box', box_names, box_atoms, BOXD)
    out.append(txt)
    out.append('/-! ### Enclosures at `(φ₀, θ₀) = (0.0391773648, 0.6813015094)` -/\n')
    res0, txt0 = gen_regime('z0', z0_names, z0_atoms, Z0D)
    out.append(txt0)
    out.append('/-! ### Enclosures near `(φ₀, θ₀)` -/\n')
    rest, txtt = gen_regime('tiny', tiny_names, tiny_atoms, TD)
    out.append(txtt)
    out.append(FOOTER)
    open(__import__('os').path.join(__import__('os').path.dirname(__file__), '..', '..', 'MovingSofaOptimality', 'External', 'Romik', 'Num.lean'), 'w').write(wrap_text('\n'.join(out)))
    for n in box_names[-4:]: print(n, fmt(res[n][0]), fmt(res[n][1]))
    for n in z0_names[-2:]: print(n, fmt(res0[n][0]), fmt(res0[n][1]))
    for n in tiny_names: print(n, fmt(rest[n][0]), fmt(rest[n][1]))
