#!/usr/bin/env python3
"""Recompute the cutoff inequalities and compare a compact invariant receipt.

This does not verify the analytic proofs that supply the geometric identities.
The full rational margins are regenerated by check_cutoff_radii.py, while this
receipt hashes their exact values instead of storing hundreds of repeated digits.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import subprocess
import sys
from fractions import Fraction
from pathlib import Path

HERE=Path(__file__).resolve().parent


def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--expect',type=Path,help='compare a committed summary after recomputation')
    args=parser.parse_args()
    subprocess.run([sys.executable,str(HERE/'check_cutoff_radii.py')],check=True)
    raw=json.loads((HERE/'cutoff-radius-checks.json').read_text())
    assert raw['status']=='passed'
    assert raw['checks']==sum(raw['groups'].values())
    assert all(Fraction(x)>0 for x in raw['exact_positive_margins'].values())
    code=(HERE/'check_cutoff_radii.py').read_bytes()
    assert hashlib.sha256(code).hexdigest()==raw['source_sha256']
    invariants={key:value for key,value in raw.items() if key!='python'}
    encoded=json.dumps(invariants,sort_keys=True,separators=(',',':')).encode()
    summary={
        'status':'passed_after_recomputation',
        'checks':raw['checks'],
        'groups':raw['groups'],
        'cutoff':raw['proposed_cutoff'],
        'reference_enclosures':raw['reference_enclosures'],
        'positive_margin_names':list(raw['exact_positive_margins']),
        'full_invariants_sha256':hashlib.sha256(encoded).hexdigest(),
        'checker_sha256':raw['source_sha256'],
        'checker_git_blob':raw['source_git_blob'],
        'interval_backend_sha256':raw['backend_sha256'],
        'replay_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'scope':raw['scope'],
        'not_verified':raw['not_verified'],
    }
    if args.expect:
        expected=json.loads(args.expect.read_text())
        if expected!=summary:
            raise AssertionError('recomputed invariant receipt does not match --expect')
    output=HERE/'cutoff-radius-summary.json'
    output.write_text(json.dumps(summary,indent=2)+'\n')
    print(json.dumps({'status':summary['status'],'checks':summary['checks'],
                      'full_invariants_sha256':summary['full_invariants_sha256'],
                      'compared_to_expect':args.expect is not None},indent=2))


if __name__=='__main__':
    main()
